# Generated by Django 5.0.14 on 2026-09-12 11:46

from django.db import migrations, models

# Keys every system role gains. Existing keys are never overwritten: owners
# may have customised their roles, and this must only *add*.
WAREHOUSE_DEFAULTS = {
    "owner": {"warehouse": ["create", "read", "update", "delete"], "warehouse_logs": ["create", "read", "update", "delete"]},
    "manager": {"warehouse": ["create", "read", "update", "delete"], "warehouse_logs": ["create", "read", "update", "delete"]},
    "kitchen": {"warehouse": ["read"], "warehouse_logs": ["create", "read", "update"]},
    "bar": {"warehouse": ["read"], "warehouse_logs": ["create", "read", "update"]},
    "waiter": {"warehouse_logs": ["create", "read", "update"]},
}
WAREHOUSE_MANAGER = {
    "menu": ["read", "update"],
    "orders": ["read"],
    "warehouse": ["create", "read", "update", "delete"],
    "warehouse_logs": ["create", "read", "update", "delete"],
}


def backfill(apps, schema_editor):
    StaffRole = apps.get_model("staff", "StaffRole")
    Restaurant = apps.get_model("tenants", "Restaurant")
    for role in StaffRole.objects.filter(is_system_role=True, name__in=list(WAREHOUSE_DEFAULTS)):
        perms = dict(role.permissions or {})
        changed = False
        for resource, actions in WAREHOUSE_DEFAULTS[role.name].items():
            if resource not in perms:
                perms[resource] = list(actions)
                changed = True
        if changed:
            role.permissions = perms
            role.save(update_fields=["permissions"])
    for restaurant_id in Restaurant.objects.values_list("id", flat=True):
        StaffRole.objects.get_or_create(
            restaurant_id=restaurant_id,
            name="warehouse_manager",
            defaults={"permissions": WAREHOUSE_MANAGER, "is_system_role": True},
        )


def unbackfill(apps, schema_editor):
    StaffRole = apps.get_model("staff", "StaffRole")
    StaffRole.objects.filter(name="warehouse_manager", members__isnull=True).delete()
    for role in StaffRole.objects.filter(is_system_role=True):
        perms = dict(role.permissions or {})
        perms.pop("warehouse", None)
        perms.pop("warehouse_logs", None)
        role.permissions = perms
        role.save(update_fields=["permissions"])


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
        ("tenants", "0014_warehouse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffrole",
            name="name",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("warehouse_manager", "Warehouse Manager"),
                    ("kitchen", "Kitchen Staff"),
                    ("bar", "Bar Staff"),
                    ("waiter", "Waiter"),
                    ("custom", "Custom Role"),
                ],
                default="waiter",
                max_length=50,
            ),
        ),
        migrations.RunPython(backfill, unbackfill),
    ]
