# Generated by Django 5.0.14 on 2026-09-12 13:14

from django.db import migrations, models


def name_custom_roles(apps, schema_editor):
    """Custom roles must carry a display name before the per-restaurant uniqueness constraint lands."""
    StaffRole = apps.get_model("staff", "StaffRole")
    for role in StaffRole.objects.filter(name="custom").order_by("created_at"):
        if not (role.display_name or "").strip():
            role.display_name = f"Custom role {str(role.pk)[:6]}"
            role.save(update_fields=["display_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_warehouse"),
        ("tenants", "0015_modules"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="staffrole",
            unique_together=set(),
        ),
        migrations.RunPython(name_custom_roles, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="staffrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("name", "custom"), _negated=True),
                fields=("restaurant", "name"),
                name="staff_role_system_name_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="staffrole",
            constraint=models.UniqueConstraint(
                condition=models.Q(("name", "custom")),
                fields=("restaurant", "display_name"),
                name="staff_role_custom_display_name_unique",
            ),
        ),
    ]
