# Generated by Django 5.0.14 on 2025-12-02 01:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0002_alter_menucategorytranslation_options_and_more"),
        ("tenants", "0003_alter_restaurant_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteRestaurant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_restaurants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite Restaurant",
                "verbose_name_plural": "Favorite Restaurants",
                "db_table": "favorite_restaurants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FavoriteMenuItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="favorited_by", to="menu.menuitem"
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_menu_items",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_menu_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite Menu Item",
                "verbose_name_plural": "Favorite Menu Items",
                "db_table": "favorite_menu_items",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "restaurant"], name="favorite_me_user_id_0f8904_idx"),
                    models.Index(fields=["user", "created_at"], name="favorite_me_user_id_cd2468_idx"),
                    models.Index(fields=["menu_item"], name="favorite_me_menu_it_834249_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="favoritemenuitem",
            constraint=models.UniqueConstraint(fields=("user", "menu_item"), name="unique_user_favorite_menu_item"),
        ),
        migrations.AddIndex(
            model_name="favoriterestaurant",
            index=models.Index(fields=["user", "created_at"], name="favorite_re_user_id_d5665b_idx"),
        ),
        migrations.AddIndex(
            model_name="favoriterestaurant",
            index=models.Index(fields=["restaurant"], name="favorite_re_restaur_498d08_idx"),
        ),
        migrations.AddConstraint(
            model_name="favoriterestaurant",
            constraint=models.UniqueConstraint(fields=("user", "restaurant"), name="unique_user_favorite_restaurant"),
        ),
    ]
