# Generated by Django 5.0.14 on 2026-09-12 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0005_delivery_platform_api"),
        ("orders", "0010_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryPlatformsPage",
            fields=[],
            options={
                "verbose_name": "Delivery platforms",
                "verbose_name_plural": "Delivery platforms",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("inventory.restaurantdeliveryplatform",),
        ),
        migrations.CreateModel(
            name="PlatformMenuSync",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("processing", "Processing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.CharField(blank=True, default="", max_length=100)),
                ("product_count", models.PositiveIntegerField(default=0)),
                ("request", models.JSONField(blank=True, default=dict)),
                ("response", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_syncs",
                        to="inventory.restaurantdeliveryplatform",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu sync",
                "verbose_name_plural": "Menu syncs",
                "db_table": "delivery_menu_syncs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryPlatformEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_id",
                    models.CharField(help_text="platform:order_id:kind -- deduplicates retries.", max_length=150),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("order_created", "Order received"),
                            ("order_cancelled", "Order cancelled by platform"),
                            ("status_pushed", "Status pushed"),
                            ("menu_status", "Menu sync status"),
                            ("cancel_requested", "Cancellation requested by restaurant"),
                        ],
                        max_length=30,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="inventory.restaurantdeliveryplatform",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_events",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform event",
                "verbose_name_plural": "Platform events",
                "db_table": "delivery_platform_events",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["link", "created_at"], name="delivery_pl_link_id_66b7af_idx")],
                "unique_together": {("link", "event_id")},
            },
        ),
    ]
