# Generated by Django 5.0.14 on 2026-09-12 17:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_event_kinds"),
        ("inventory", "0006_store_paused_until"),
        ("tenants", "0019_delivery_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuImport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source",
                    models.CharField(
                        choices=[("glovo", "Glovo"), ("wolt", "Wolt"), ("bolt_food", "Bolt Food")], max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("fetching", "Fetching"),
                            ("previewed", "Previewed"),
                            ("images", "Importing images"),
                            ("imported", "Imported"),
                            ("failed", "Failed"),
                            ("failed_apply", "Import failed"),
                        ],
                        default="fetching",
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=dict)),
                (
                    "raw",
                    models.JSONField(blank=True, default=dict, help_text="The platform's menu payload as received."),
                ),
                ("preview", models.JSONField(blank=True, default=dict)),
                ("stats", models.JSONField(blank=True, default=dict)),
                (
                    "images",
                    models.JSONField(
                        blank=True, default=list, help_text="[[menu_item_id, url], ...] still to download."
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_imports",
                        to="inventory.restaurantdeliveryplatform",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_imports",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu import",
                "verbose_name_plural": "Menu imports",
                "db_table": "delivery_menu_imports",
                "ordering": ["-created_at"],
            },
        ),
    ]
