# Generated by Django 5.0.14 on 2025-12-02 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('tables', '0003_tablesession_host_tablesession_invite_code_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_restaur_0aeb84_idx',
            old_name='orders_rest_status_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_restaur_696987_idx',
            old_name='orders_rest_created_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_order_n_1336be_idx',
            old_name='orders_order_num_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='session_guest',
            field=models.ForeignKey(blank=True, help_text='The guest at the table who placed this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tables.tablesessionguest'),
        ),
    ]
