# Generated by Django 5.0.14 on 2026-04-19 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_order_status'),
        ('reservations', '0002_alter_reservationhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reservation',
            field=models.ForeignKey(blank=True, help_text='Optional — set when this order was placed as part of a reservation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='reservations.reservation'),
        ),
    ]
