# Generated by Django 5.0.14 on 2026-04-20 20:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_reservation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="server",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member credited with serving this order (for tip distribution).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="served_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tip_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Optional gratuity paid on top of subtotal/tax/service.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tip_distribution",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Phase-3 tip allocation map. {user_id_or_pool: decimal_amount}. Unassigned tips accrue to the server FK or the restaurant pool.",
            ),
        ),
    ]
