# Generated by Django 5.0.14 on 2026-09-12 14:58

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_wallet_applied"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderDiscount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("manual", "Manual"), ("loyalty_tier", "Loyalty tier"), ("promo", "Promotion")],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("percent", "Percent"), ("fixed", "Fixed amount")], default="percent", max_length=10
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("reason_text", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={
                "db_table": "order_discounts",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
