# Generated by Django 5.0.14 on 2026-09-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_discounts_voids"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="prices_include_vat",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="vat_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
