# Generated by Django 5.0.14 on 2026-09-12 16:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_vat_snapshot"),
        ("reservations", "0002_alter_reservationhistory_options_and_more"),
        ("tables", "0009_floor_plan"),
        ("tenants", "0019_delivery_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="external_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="platform_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="order",
            name="source",
            field=models.CharField(
                choices=[
                    ("web", "Website"),
                    ("qr", "QR table"),
                    ("pos", "POS"),
                    ("glovo", "Glovo"),
                    ("wolt", "Wolt"),
                    ("bolt_food", "Bolt Food"),
                ],
                db_index=True,
                default="web",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("restaurant", "source", "external_id"),
                name="order_external_id_unique_per_source",
            ),
        ),
    ]
