# Generated by Django 5.0.14 on 2026-09-12 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_source"),
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdiscount",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_discounts",
                to="promotions.promotion",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="promotions.promotion",
            ),
        ),
    ]
