# Generated by Django 5.0.14 on 2026-09-13 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordering", "0001_initial"),
        ("orders", "0011_promotions"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address_json",
            field=models.JSONField(
                blank=True, default=dict, help_text="Structured address: street, building, entrance, floor, apartment."
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_instructions",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_lat",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_lng",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="ordering.deliveryzone",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="packaging_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="scheduled_for",
            field=models.DateTimeField(
                blank=True, db_index=True, help_text="Pickup / delivery time the guest chose; empty = ASAP.", null=True
            ),
        ),
    ]
