# Generated by Django 5.0.14 on 2026-09-13 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giftcards", "0001_initial"),
        ("orders", "0012_fulfilment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="gift_card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="giftcards.giftcard",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="gift_card_applied",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Paid from a gift card at checkout (a gift_card payment).",
                max_digits=10,
            ),
        ),
    ]
