# Generated by Django 5.0.14 on 2026-09-12 18:35

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0006_store_paused_until"),
        ("tenants", "0022_purchasing_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("contact_name", models.CharField(blank=True, default="", max_length=120)),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, default="", help_text="ს/კ of the supplier (waybills).", max_length=20
                    ),
                ),
                ("address", models.CharField(blank=True, default="", max_length=300)),
                (
                    "payment_terms",
                    models.CharField(
                        blank=True, default="", help_text="E.g. 'on delivery', '14 days'.", max_length=120
                    ),
                ),
                (
                    "lead_days",
                    models.PositiveSmallIntegerField(default=1, help_text="Days between ordering and delivery."),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="suppliers", to="tenants.restaurant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "db_table": "purchasing_suppliers",
                "ordering": ["name"],
                "unique_together": {("restaurant", "name")},
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("number", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent to supplier"),
                            ("partial", "Partially received"),
                            ("received", "Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("expected_on", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="", help_text="Shown to the supplier.")),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("sent_via", models.CharField(blank=True, default="", max_length=20)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference",
                    models.CharField(
                        blank=True, default="", help_text="Supplier invoice / waybill no.", max_length=100
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="purchasing.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase order",
                "verbose_name_plural": "Purchase orders",
                "db_table": "purchasing_orders",
                "ordering": ["-created_at"],
                "unique_together": {("restaurant", "number")},
            },
        ),
        migrations.CreateModel(
            name="SupplierItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("supplier_sku", models.CharField(blank=True, default="", max_length=60)),
                (
                    "pack_qty",
                    models.DecimalField(
                        decimal_places=4, default=1, help_text="Units per pack (a 10 kg bag = 10).", max_digits=12
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4, default=0, help_text="Per unit, latest known.", max_digits=12
                    ),
                ),
                ("last_price_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_preferred",
                    models.BooleanField(default=False, help_text="The buy list orders from this supplier."),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_items",
                        to="inventory.stockitem",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="items", to="purchasing.supplier"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        help_text="Unit the price is per.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.unitofmeasure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier price",
                "verbose_name_plural": "Supplier prices",
                "db_table": "purchasing_supplier_items",
                "unique_together": {("supplier", "stock_item")},
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.0001"))],
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=4, default=0, help_text="Per unit.", max_digits=12)),
                ("received_qty", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="purchasing.purchaseorder"
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="po_lines", to="inventory.stockitem"
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="inventory.unitofmeasure"
                    ),
                ),
                (
                    "supplier_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="po_lines",
                        to="purchasing.supplieritem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase order line",
                "verbose_name_plural": "Purchase order lines",
                "db_table": "purchasing_order_lines",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PriceObservation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("source", models.CharField(default="receive", max_length=20)),
                ("observed_at", models.DateTimeField()),
                (
                    "supplier_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="purchasing.supplieritem",
                    ),
                ),
            ],
            options={
                "db_table": "purchasing_price_history",
                "ordering": ["-observed_at"],
            },
        ),
    ]
