# Generated by Django 5.0.14 on 2025-12-02 00:58

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tables", "0002_rename_tables_rest_status_idx_tables_restaur_6a4c6c_idx"),
        ("tenants", "0003_alter_restaurant_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("guest_name", models.CharField(max_length=255)),
                ("guest_email", models.EmailField(blank=True, max_length=254)),
                ("guest_phone", models.CharField(max_length=20)),
                ("reservation_date", models.DateField(db_index=True)),
                ("reservation_time", models.TimeField(db_index=True)),
                ("party_size", models.PositiveSmallIntegerField()),
                (
                    "duration",
                    models.DurationField(
                        default=datetime.timedelta(seconds=7200), help_text="Expected duration of the reservation"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("waitlist", "Waitlisted"),
                            ("seated", "Seated"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("phone", "Phone"),
                            ("walk_in", "Walk-in"),
                            ("third_party", "Third-party Platform"),
                            ("app", "Mobile App"),
                        ],
                        default="website",
                        max_length=20,
                    ),
                ),
                ("confirmation_code", models.CharField(editable=False, max_length=12, unique=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("special_requests", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True, help_text="Private notes visible only to staff")),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("seated_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Registered user making the reservation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="tables.table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation",
                "verbose_name_plural": "Reservations",
                "db_table": "reservations",
                "ordering": ["reservation_date", "reservation_time"],
            },
        ),
        migrations.CreateModel(
            name="ReservationBlockedTime",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("holiday", "Holiday"),
                            ("private_event", "Private Event"),
                            ("maintenance", "Maintenance"),
                            ("staff_shortage", "Staff Shortage"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_pattern",
                    models.JSONField(blank=True, help_text="Recurrence pattern (e.g., weekly, monthly)", null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_blocked_times",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_times",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "tables",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to block all tables",
                        related_name="blocked_times",
                        to="tables.table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blocked Time",
                "verbose_name_plural": "Blocked Times",
                "db_table": "reservation_blocked_times",
                "ordering": ["start_datetime"],
            },
        ),
        migrations.CreateModel(
            name="ReservationHistory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("previous_status", models.CharField(blank=True, max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation History",
                "verbose_name_plural": "Reservation Histories",
                "db_table": "reservation_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReservationSettings",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accepts_reservations", models.BooleanField(default=True)),
                ("min_party_size", models.PositiveSmallIntegerField(default=1)),
                ("max_party_size", models.PositiveSmallIntegerField(default=20)),
                (
                    "reservation_duration",
                    models.DurationField(
                        default=datetime.timedelta(seconds=7200), help_text="Default duration for a reservation"
                    ),
                ),
                (
                    "advance_booking_days",
                    models.PositiveSmallIntegerField(default=30, help_text="How many days in advance can guests book"),
                ),
                (
                    "min_advance_hours",
                    models.PositiveSmallIntegerField(
                        default=2, help_text="Minimum hours in advance required for booking"
                    ),
                ),
                (
                    "buffer_minutes",
                    models.PositiveSmallIntegerField(
                        default=15, help_text="Buffer time between reservations on same table"
                    ),
                ),
                (
                    "slot_interval_minutes",
                    models.PositiveSmallIntegerField(
                        default=30, help_text="Time slot intervals (e.g., every 30 minutes)"
                    ),
                ),
                (
                    "cancellation_deadline_hours",
                    models.PositiveSmallIntegerField(
                        default=24, help_text="Hours before reservation when cancellation is allowed"
                    ),
                ),
                (
                    "require_confirmation",
                    models.BooleanField(default=False, help_text="Require restaurant confirmation for reservations"),
                ),
                (
                    "auto_confirm_threshold",
                    models.PositiveSmallIntegerField(
                        default=4, help_text="Auto-confirm reservations for parties up to this size"
                    ),
                ),
                ("send_reminder", models.BooleanField(default=True)),
                ("reminder_hours_before", models.PositiveSmallIntegerField(default=24)),
                (
                    "max_daily_reservations",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Maximum reservations per day (0 = unlimited)"
                    ),
                ),
                (
                    "max_hourly_reservations",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Maximum reservations per hour (0 = unlimited)"
                    ),
                ),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_settings",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reservation Settings",
                "verbose_name_plural": "Reservation Settings",
                "db_table": "reservation_settings",
            },
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["restaurant", "reservation_date"], name="reservation_restaur_f79f12_idx"),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["restaurant", "status"], name="reservation_restaur_c01ce3_idx"),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["customer"], name="reservation_custome_4e1d8c_idx"),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["confirmation_code"], name="reservation_confirm_a9b9b8_idx"),
        ),
    ]
