# Generated by Django 5.0.14 on 2026-04-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reservation History', 'verbose_name_plural': 'Reservation History'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('waitlist', 'Waitlisted'), ('seated', 'Seated'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=20),
        ),
    ]
