# Generated by Django 5.0.14 on 2025-12-02 00:00

import django.core.validators
import django.db.models.deletion
import parler.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_expand_restaurant_add_hours"),
    ]

    operations = [
        # MenuCategory
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="menu/categories/"),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_categories",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "menu_categories",
                "ordering": ["display_order", "created_at"],
                "verbose_name_plural": "Menu Categories",
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name="MenuCategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "master",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="menu.menucategory",
                    ),
                ),
            ],
            options={
                "db_table": "menu_categories_translation",
                "verbose_name": "Menu Category Translation",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
        ),
        # MenuItem
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="menu/items/"),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="Featured items appear prominently in the menu",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "preparation_time_minutes",
                    models.PositiveIntegerField(default=15, help_text="Estimated preparation time in minutes"),
                ),
                (
                    "preparation_station",
                    models.CharField(
                        choices=[
                            ("kitchen", "Kitchen"),
                            ("bar", "Bar"),
                            ("both", "Both"),
                        ],
                        default="kitchen",
                        max_length=10,
                    ),
                ),
                (
                    "calories",
                    models.PositiveIntegerField(blank=True, help_text="Calorie count per serving", null=True),
                ),
                (
                    "allergens",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allergen codes (e.g., ['gluten', 'dairy'])",
                    ),
                ),
                ("is_vegetarian", models.BooleanField(default=False)),
                ("is_vegan", models.BooleanField(default=False)),
                ("is_gluten_free", models.BooleanField(default=False)),
                ("is_spicy", models.BooleanField(default=False)),
                (
                    "spicy_level",
                    models.PositiveSmallIntegerField(default=0, help_text="Spicy level 0-5 (0 = not spicy)"),
                ),
                ("track_inventory", models.BooleanField(default=False)),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="menu.menucategory",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "menu_items",
                "ordering": ["display_order", "created_at"],
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["restaurant", "is_available"],
                name="menu_items_restaur_7b7d3c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="menuitem",
            index=models.Index(
                fields=["category", "is_available"],
                name="menu_items_categor_2f8b6a_idx",
            ),
        ),
        migrations.CreateModel(
            name="MenuItemTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "master",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="menu.menuitem",
                    ),
                ),
            ],
            options={
                "db_table": "menu_items_translation",
                "verbose_name": "Menu Item Translation",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
        ),
        # ModifierGroup
        migrations.CreateModel(
            name="ModifierGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "selection_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Selection"),
                            ("multiple", "Multiple Selection"),
                        ],
                        default="single",
                        max_length=10,
                    ),
                ),
                (
                    "min_selections",
                    models.PositiveSmallIntegerField(default=0, help_text="Minimum number of selections required"),
                ),
                (
                    "max_selections",
                    models.PositiveSmallIntegerField(default=1, help_text="Maximum number of selections allowed"),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Customer must make a selection from this group",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifier_groups",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "modifier_groups",
                "ordering": ["display_order", "created_at"],
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name="ModifierGroupTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "master",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="menu.modifiergroup",
                    ),
                ),
            ],
            options={
                "db_table": "modifier_groups_translation",
                "verbose_name": "Modifier Group Translation",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
        ),
        # Modifier
        migrations.CreateModel(
            name="Modifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Price adjustment (can be positive or negative)",
                        max_digits=10,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(default=False, help_text="Pre-selected by default"),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifiers",
                        to="menu.modifiergroup",
                    ),
                ),
            ],
            options={
                "db_table": "modifiers",
                "ordering": ["display_order", "created_at"],
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name="ModifierTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(db_index=True, max_length=15, verbose_name="Language"),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "master",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="menu.modifier",
                    ),
                ),
            ],
            options={
                "db_table": "modifiers_translation",
                "verbose_name": "Modifier Translation",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
        ),
        # MenuItemModifierGroup
        migrations.CreateModel(
            name="MenuItemModifierGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifier_groups_link",
                        to="menu.menuitem",
                    ),
                ),
                (
                    "modifier_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items_link",
                        to="menu.modifiergroup",
                    ),
                ),
            ],
            options={
                "db_table": "menu_item_modifier_groups",
                "ordering": ["display_order"],
                "unique_together": {("menu_item", "modifier_group")},
            },
        ),
    ]
