# Generated by Django 5.0.14 on 2025-12-02 01:34

import django.db.models.deletion
import parler.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menucategorytranslation",
            options={"default_permissions": (), "managed": True, "verbose_name": "menu category Translation"},
        ),
        migrations.AlterModelOptions(
            name="menuitemtranslation",
            options={"default_permissions": (), "managed": True, "verbose_name": "menu item Translation"},
        ),
        migrations.AlterModelOptions(
            name="modifiergrouptranslation",
            options={"default_permissions": (), "managed": True, "verbose_name": "modifier group Translation"},
        ),
        migrations.AlterModelOptions(
            name="modifiertranslation",
            options={"default_permissions": (), "managed": True, "verbose_name": "modifier Translation"},
        ),
        migrations.RenameIndex(
            model_name="menuitem",
            new_name="menu_items_restaur_d2ad1f_idx",
            old_name="menu_items_restaur_7b7d3c_idx",
        ),
        migrations.RenameIndex(
            model_name="menuitem",
            new_name="menu_items_categor_841ca3_idx",
            old_name="menu_items_categor_2f8b6a_idx",
        ),
        migrations.AlterField(
            model_name="menucategorytranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="menu.menucategory",
            ),
        ),
        migrations.AlterField(
            model_name="menuitemtranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="menu.menuitem",
            ),
        ),
        migrations.AlterField(
            model_name="modifiergrouptranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="menu.modifiergroup",
            ),
        ),
        migrations.AlterField(
            model_name="modifiertranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="menu.modifier",
            ),
        ),
    ]
