# Generated by Django 5.0.14 on 2026-09-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0004_modifiergroup_internal_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="auto_disabled_by_stock",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Set by the warehouse when a recipe ingredient has run out; cleared when it is restocked.",
            ),
        ),
        migrations.AddField(
            model_name="modifier",
            name="auto_disabled_by_stock",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Set by the warehouse when a recipe ingredient has run out; cleared when it is restocked.",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="stock_quantity",
            field=models.PositiveIntegerField(default=0, help_text="Deprecated: see Warehouse recipes."),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="track_inventory",
            field=models.BooleanField(default=False, help_text="Deprecated: see Warehouse recipes."),
        ),
    ]
