# Generated by Django 5.0.14 on 2026-09-12 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0005_warehouse"),
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menucategory",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                help_text="Only shown / orderable inside this window (e.g. Breakfast).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="promotions.menuschedule",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_combo",
            field=models.BooleanField(
                default=False, help_text="Set menu: the warehouse consumes the components' recipes."
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                help_text="Only orderable inside this window; empty = follows the category.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="promotions.menuschedule",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="unavailable_until",
            field=models.DateTimeField(
                blank=True, help_text="'86 today': hidden from ordering until this moment.", null=True
            ),
        ),
    ]
