# Generated by Django 5.0.14 on 2026-09-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_referral_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="marketing_opt_in",
            field=models.BooleanField(
                default=False, help_text="Offers and news from restaurants I visit (SMS / email)."
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="marketing_opt_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
