# Generated by Django 5.0.14 on 2026-09-12 18:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("staff", "0006_timekeeping"),
        ("tenants", "0023_timekeeping_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RotaShift",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField(db_index=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(help_text="Earlier than the start = the shift ends after midnight.")),
                (
                    "label",
                    models.CharField(
                        blank=True, default="", help_text="E.g. 'Bar', 'Kitchen', 'Floor'.", max_length=60
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rota_shifts", to="tenants.restaurant"
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rota_shifts", to="staff.staffmember"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rota shift",
                "verbose_name_plural": "Rota",
                "db_table": "timekeeping_rota_shifts",
                "ordering": ["date", "start_time"],
                "indexes": [models.Index(fields=["restaurant", "date"], name="timekeeping_restaur_417fa3_idx")],
            },
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("clock_in", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("clock_out", models.DateTimeField(blank=True, null=True)),
                ("break_minutes", models.PositiveSmallIntegerField(default=0)),
                (
                    "source",
                    models.CharField(
                        choices=[("pos", "POS"), ("admin", "Admin"), ("auto", "Auto-closed")],
                        default="pos",
                        max_length=10,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "auto_closed",
                    models.BooleanField(default=False, help_text="Closed by the system after 16 hours; check it."),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_entries",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="time_entries", to="staff.staffmember"
                    ),
                ),
            ],
            options={
                "verbose_name": "Time entry",
                "verbose_name_plural": "Time entries",
                "db_table": "timekeeping_entries",
                "ordering": ["-clock_in"],
                "indexes": [
                    models.Index(fields=["restaurant", "clock_in"], name="timekeeping_restaur_2db7b8_idx"),
                    models.Index(fields=["staff_member", "clock_out"], name="timekeeping_staff_m_f5e34c_idx"),
                ],
            },
        ),
    ]
