# Generated by Django 5.0.14 on 2026-09-13 08:10

import apps.houseaccounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0002_seed_beat"),
        ("orders", "0013_gift_card"),
        ("payments", "0009_terminal_fk"),
        ("tenants", "0028_gift_house_modules"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseAccount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="Person or company on the account.", max_length=120)),
                ("company", models.CharField(blank=True, default="", max_length=120)),
                ("tax_id", models.CharField(blank=True, default="", max_length=20)),
                ("phone", models.CharField(blank=True, db_index=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "credit_limit",
                    models.DecimalField(decimal_places=2, default=0, help_text="0 = no limit.", max_digits=10),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, help_text="Amount owed to you.", max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("suspended", "Suspended"), ("closed", "Closed")],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "billing_day",
                    models.PositiveSmallIntegerField(default=1, help_text="Day of month the statement goes out."),
                ),
                (
                    "authorised_names",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Who may charge to this account (comma separated).",
                        max_length=300,
                    ),
                ),
                ("require_signature", models.BooleanField(default=False, help_text="Ask who signed at the POS.")),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "token",
                    models.CharField(
                        default=apps.houseaccounts.models.new_token, editable=False, max_length=40, unique=True
                    ),
                ),
                ("last_payment_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="house_accounts",
                        to="crm.customer",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="house_accounts",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "House account",
                "verbose_name_plural": "House accounts",
                "db_table": "house_accounts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HouseAccountEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("charge", "Charge"),
                            ("payment", "Payment received"),
                            ("adjustment", "Adjustment"),
                            ("writeoff", "Written off"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, help_text="Signed: + increases what is owed.", max_digits=10),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=10)),
                ("signed_by", models.CharField(blank=True, default="", max_length=120)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="houseaccounts.houseaccount",
                    ),
                ),
                (
                    "by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="house_account_entries",
                        to="orders.order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="house_account_entries",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "House account entry",
                "verbose_name_plural": "House account entries",
                "db_table": "house_account_entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HouseAccountStatement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("opening", models.DecimalField(decimal_places=2, max_digits=10)),
                ("charges", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payments", models.DecimalField(decimal_places=2, max_digits=10)),
                ("adjustments", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("closing", models.DecimalField(decimal_places=2, max_digits=10)),
                ("lines", models.JSONField(blank=True, default=list)),
                (
                    "token",
                    models.CharField(
                        default=apps.houseaccounts.models.new_token, editable=False, max_length=40, unique=True
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("sent_to", models.CharField(blank=True, default="", max_length=254)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="houseaccounts.houseaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Statement",
                "verbose_name_plural": "Statements",
                "db_table": "house_account_statements",
                "ordering": ["-period_end"],
            },
        ),
        migrations.AddIndex(
            model_name="houseaccount",
            index=models.Index(fields=["restaurant", "status"], name="house_accou_restaur_517666_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="houseaccountstatement",
            unique_together={("account", "period_start", "period_end")},
        ),
    ]
