# Generated by Django 5.0.14 on 2026-04-20 17:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0003_alter_menucategory_options_and_more"),
        ("orders", "0004_order_reservation"),
        ("tenants", "0010_alter_citytranslation_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyProgram",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "threshold",
                    models.PositiveIntegerField(default=5, help_text="Punches required to unlock the reward."),
                ),
                ("reward_quantity", models.PositiveIntegerField(default=1)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code_ttl_seconds",
                    models.PositiveIntegerField(
                        default=86400, help_text="How long a generated redemption code is valid."
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_programs",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "reward_item",
                    models.ForeignKey(
                        help_text="Item the customer gets free when the threshold is hit.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loyalty_reward_programs",
                        to="menu.menuitem",
                    ),
                ),
                (
                    "trigger_item",
                    models.ForeignKey(
                        help_text="Buying this item earns punches.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loyalty_trigger_programs",
                        to="menu.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyCounter",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone_number", models.CharField(blank=True, db_index=True, default="", max_length=32)),
                ("punches", models.PositiveIntegerField(default=0)),
                ("last_earned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_counters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counters",
                        to="loyalty.loyaltyprogram",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="LoyaltyRedemption",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone_number", models.CharField(blank=True, default="", max_length=32)),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("redeemed", "Redeemed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "counter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="loyalty.loyaltycounter",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="loyalty.loyaltyprogram",
                    ),
                ),
                (
                    "redeemed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loyalty_confirmations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "redeemed_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loyalty_redemptions",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loyalty_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="loyaltycounter",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("program", "user"),
                name="loyalty_counter_unique_program_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="loyaltycounter",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True), models.Q(("phone_number", ""), _negated=True)),
                fields=("program", "phone_number"),
                name="loyalty_counter_unique_program_phone",
            ),
        ),
    ]
