# Generated by Django 5.0.14 on 2026-04-21 21:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("loyalty", "0001_initial"),
        ("orders", "0005_order_server_order_tip_amount_order_tip_distribution"),
        ("tenants", "0012_restaurant_accepts_platform_loyalty"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformLoyaltyTier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=40, unique=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("name_ka", models.CharField(max_length=80)),
                ("name_en", models.CharField(max_length=80)),
                ("name_ru", models.CharField(max_length=80)),
                (
                    "min_points",
                    models.PositiveIntegerField(help_text="Inclusive lower bound of points-in-window for this tier."),
                ),
                (
                    "discount_percent",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Integer 0–100. Applied to subtotal at checkout."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Platform loyalty tier",
                "verbose_name_plural": "Platform loyalty tiers",
                "db_table": "platform_loyalty_tiers",
                "ordering": ["min_points"],
            },
        ),
        migrations.CreateModel(
            name="PlatformLoyaltyLedger",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("points", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=8)),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.CharField(choices=[("bog", "BOG"), ("cash", "Cash settle")], default="bog", max_length=16),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_loyalty_events",
                        to="orders.order",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_loyalty_events",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_loyalty_events",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform loyalty ledger entry",
                "verbose_name_plural": "Platform loyalty ledger",
                "db_table": "platform_loyalty_ledger",
                "ordering": ["-earned_at"],
                "indexes": [models.Index(fields=["user", "earned_at"], name="platform_lo_user_id_a6e6a0_idx")],
            },
        ),
    ]
