# Generated by Django 5.0.14 on 2026-09-13 07:50

import apps.waitlist.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0002_alter_reservationhistory_options_and_more"),
        ("tables", "0009_floor_plan"),
        ("tenants", "0027_waitlist_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistSettings",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_wait_minutes",
                    models.PositiveSmallIntegerField(
                        default=15, help_text="Quoted wait when there is no history to estimate from."
                    ),
                ),
                (
                    "notify_expire_minutes",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="A notified guest who does not show up within this time is marked no-show.",
                    ),
                ),
                (
                    "allow_self_join",
                    models.BooleanField(default=True, help_text="Guests can join from the QR at the door."),
                ),
                ("max_party_size", models.PositiveSmallIntegerField(default=12)),
                (
                    "sms_on_join",
                    models.BooleanField(default=True, help_text="Text the guest their place in line when added."),
                ),
                (
                    "sms_on_ready",
                    models.BooleanField(default=True, help_text="Text the guest when the table is ready."),
                ),
                ("join_token", models.CharField(default=apps.waitlist.models.new_token, editable=False, max_length=40)),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_settings",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Waitlist settings",
                "verbose_name_plural": "Waitlist settings",
                "db_table": "waitlist_settings",
            },
        ),
        migrations.CreateModel(
            name="WaitlistSettingsPage",
            fields=[],
            options={
                "verbose_name": "Waitlist settings",
                "verbose_name_plural": "Waitlist settings",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("waitlist.waitlistsettings",),
        ),
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True, help_text="Local service day.")),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("party_size", models.PositiveSmallIntegerField(default=2)),
                ("quoted_minutes", models.PositiveSmallIntegerField(default=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("notified", "Table ready · notified"),
                            ("seated", "Seated"),
                            ("left", "Left"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No-show"),
                        ],
                        db_index=True,
                        default="waiting",
                        max_length=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("pos", "Staff"), ("self", "Guest (QR)"), ("reservation", "From a reservation")],
                        default="pos",
                        max_length=12,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("notify_count", models.PositiveSmallIntegerField(default=0)),
                ("seated_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "token",
                    models.CharField(
                        default=apps.waitlist.models.new_token, editable=False, max_length=40, unique=True
                    ),
                ),
                ("estimated_ready_at", models.DateTimeField(blank=True, null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waitlist_entries",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waitlist_entries",
                        to="tables.tablesession",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waitlist_entries",
                        to="tables.table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Waitlist entry",
                "verbose_name_plural": "Waitlist",
                "db_table": "waitlist_entries",
                "ordering": ["date", "position", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["restaurant", "date", "status", "position"], name="waitlist_en_restaur_816493_idx"
                    )
                ],
            },
        ),
    ]
