# Generated by Django 5.0.14 on 2026-09-12 15:46

import apps.printing.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0008_discounts_voids"),
        ("payments", "0008_payment_restaurant_not_null"),
        ("tenants", "0017_printing_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="E.g. 'Kitchen pass', 'Bar', 'Till'.", max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[("kitchen", "Kitchen tickets"), ("bar", "Bar tickets"), ("receipt", "Receipts")],
                        default="kitchen",
                        max_length=10,
                    ),
                ),
                (
                    "stations",
                    models.CharField(
                        choices=[("kitchen", "Kitchen"), ("bar", "Bar"), ("both", "Kitchen + bar")],
                        default="kitchen",
                        help_text="Which items go on this printer's tickets (kitchen printers only).",
                        max_length=10,
                    ),
                ),
                ("paper", models.CharField(choices=[("80", "80 mm"), ("58", "58 mm")], default="80", max_length=2)),
                (
                    "connection",
                    models.CharField(
                        choices=[
                            ("bridge", "Print bridge (USB / LAN / Bluetooth)"),
                            ("browser", "Browser print (no bridge)"),
                        ],
                        default="bridge",
                        max_length=10,
                    ),
                ),
                (
                    "bridge_key",
                    models.CharField(
                        default=apps.printing.models.new_bridge_key, editable=False, max_length=64, unique=True
                    ),
                ),
                ("copies", models.PositiveSmallIntegerField(default=1)),
                (
                    "auto_print",
                    models.BooleanField(
                        default=True,
                        help_text="Kitchen/bar: print a ticket when an order is accepted. Receipt: print when a payment is taken.",
                    ),
                ),
                (
                    "open_drawer",
                    models.BooleanField(
                        default=False, help_text="Receipt printers: kick the cash drawer on cash payments."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, help_text="Last poll from the bridge.", null=True)),
                ("last_error", models.CharField(blank=True, default="", max_length=300)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="printers", to="tenants.restaurant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Printer",
                "verbose_name_plural": "Printers",
                "db_table": "printers",
                "ordering": ["kind", "name"],
            },
        ),
        migrations.CreateModel(
            name="PrintJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ticket", "Kitchen ticket"),
                            ("receipt", "Receipt"),
                            ("report", "Report"),
                            ("test", "Test page"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=120)),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, help_text="What was rendered (for reprints / audit)."),
                ),
                ("escpos", models.BinaryField(help_text="Rendered ESC/POS bytes the bridge writes to the device.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("printing", "Printing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("error", models.CharField(blank=True, default="", max_length=300)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("printed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_jobs",
                        to="orders.order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_jobs",
                        to="payments.payment",
                    ),
                ),
                (
                    "printer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="jobs", to="printing.printer"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="print_jobs", to="tenants.restaurant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Print job",
                "verbose_name_plural": "Print jobs",
                "db_table": "print_jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["printer", "status", "created_at"], name="print_jobs_printer_27b0c8_idx"),
                    models.Index(fields=["restaurant", "status"], name="print_jobs_restaur_a63343_idx"),
                ],
            },
        ),
    ]
