# Generated by Django 5.0.14 on 2026-09-13 07:33

import apps.terminals.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0012_fulfilment"),
        ("payments", "0008_payment_restaurant_not_null"),
        ("tables", "0009_floor_plan"),
        ("tenants", "0026_terminals_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTerminal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="E.g. 'Till 1', 'Bar terminal', 'QR at the table'.", max_length=100),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("manual", "Physical terminal (cashier confirms)"),
                            ("bog_link", "Bank of Georgia pay-by-link / QR"),
                            ("tbc_tpay", "TBC pay-by-link / QR (TPAY)"),
                            ("ecr_bridge", "ECR terminal via the terminal bridge"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "ecr_protocol",
                    models.CharField(
                        blank=True,
                        choices=[("", "—"), ("bog", "Bank of Georgia ECR"), ("tbc", "TBC ECR")],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "terminal_id",
                    models.CharField(blank=True, default="", help_text="The bank's terminal id (TID).", max_length=60),
                ),
                (
                    "connection",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Bridge device: {"device": "tcp://192.168.1.60:8000"} or serial://.',
                    ),
                ),
                ("credentials_encrypted", models.TextField(blank=True, default="")),
                (
                    "bridge_key",
                    models.CharField(
                        default=apps.terminals.models.new_bridge_key, editable=False, max_length=64, unique=True
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, help_text="Last poll from the bridge.", null=True)),
                ("last_error", models.CharField(blank=True, default="", max_length=300)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False, help_text="Preselected in the POS.")),
                (
                    "auto_receipt",
                    models.BooleanField(default=True, help_text="Print a receipt when the payment is approved."),
                ),
                (
                    "timeout_seconds",
                    models.PositiveSmallIntegerField(default=180, help_text="Give up waiting after this long."),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="terminals", to="tenants.restaurant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Card terminal",
                "verbose_name_plural": "Card terminals",
                "db_table": "terminals",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="TerminalTransaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(choices=[("sale", "Sale"), ("refund", "Refund")], default="sale", max_length=10),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tip", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("currency", models.CharField(default="GEL", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Starting"),
                            ("sent", "Sent to terminal"),
                            ("awaiting_confirm", "Waiting for confirmation"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                            ("timeout", "Timed out"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("order_ids", models.JSONField(blank=True, default=list)),
                ("external_id", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("auth_code", models.CharField(blank=True, default="", max_length=40)),
                ("card_mask", models.CharField(blank=True, default="", max_length=30)),
                ("rrn", models.CharField(blank=True, default="", max_length=40)),
                ("pay_url", models.URLField(blank=True, default="", max_length=600)),
                ("request", models.JSONField(blank=True, default=dict)),
                ("response", models.JSONField(blank=True, default=dict)),
                ("error", models.CharField(blank=True, default="", max_length=300)),
                (
                    "sent_to",
                    models.CharField(
                        blank=True, default="", help_text="Phone / email the link went to.", max_length=254
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terminal_transactions",
                        to="orders.order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terminal_transactions",
                        to="payments.payment",
                    ),
                ),
                (
                    "refund_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds",
                        to="terminals.terminaltransaction",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terminal_transactions",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terminal_transactions",
                        to="tables.tablesession",
                    ),
                ),
                (
                    "terminal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="terminals.paymentterminal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Terminal transaction",
                "verbose_name_plural": "Terminal transactions",
                "db_table": "terminal_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TerminalReconciliation",
            fields=[],
            options={
                "verbose_name": "Terminal reconciliation",
                "verbose_name_plural": "Terminal reconciliation",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("terminals.terminaltransaction",),
        ),
        migrations.AddIndex(
            model_name="terminaltransaction",
            index=models.Index(fields=["terminal", "status", "created_at"], name="terminal_tr_termina_9d7370_idx"),
        ),
        migrations.AddIndex(
            model_name="terminaltransaction",
            index=models.Index(fields=["restaurant", "status", "created_at"], name="terminal_tr_restaur_d42bc4_idx"),
        ),
    ]
