# Generated by Django 5.0.14 on 2025-12-02 00:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        # Add new fields to Restaurant
        migrations.AddField(
            model_name="restaurant",
            name="description",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in international format: +995XXXXXXXXX",
                        regex="^\\+?[1-9]\\d{1,14}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="country",
            field=models.CharField(default="Georgia", max_length=100),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="restaurants/logos/"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="restaurants/covers/"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="primary_color",
            field=models.CharField(
                default="#000000",
                max_length=7,
                validators=[django.core.validators.RegexValidator("^#[0-9A-Fa-f]{6}$", "Enter a valid hex color")],
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="secondary_color",
            field=models.CharField(
                default="#FFFFFF",
                max_length=7,
                validators=[django.core.validators.RegexValidator("^#[0-9A-Fa-f]{6}$", "Enter a valid hex color")],
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="default_currency",
            field=models.CharField(
                choices=[
                    ("GEL", "Georgian Lari"),
                    ("USD", "US Dollar"),
                    ("EUR", "Euro"),
                ],
                default="GEL",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="timezone",
            field=models.CharField(
                choices=[
                    ("Asia/Tbilisi", "Tbilisi (GMT+4)"),
                    ("Europe/London", "London (GMT)"),
                    ("Europe/Berlin", "Berlin (GMT+1)"),
                    ("America/New_York", "New York (GMT-5)"),
                ],
                default="Asia/Tbilisi",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="default_language",
            field=models.CharField(
                choices=[("ka", "Georgian"), ("en", "English"), ("ru", "Russian")],
                default="ka",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="accepts_remote_orders",
            field=models.BooleanField(
                default=True,
                help_text="Allow customers to place orders without being at the restaurant",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="accepts_reservations",
            field=models.BooleanField(default=True, help_text="Allow customers to make reservations"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="accepts_takeaway",
            field=models.BooleanField(default=True, help_text="Allow takeaway orders"),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Tax percentage to apply to orders",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="service_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Service charge percentage",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="average_rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="total_reviews",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="total_orders",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="minimum_order_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Minimum order amount for remote orders",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="average_preparation_time",
            field=models.PositiveIntegerField(default=30, help_text="Average order preparation time in minutes"),
        ),
        # Add indexes
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(fields=["slug"], name="restaurants_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(fields=["is_active"], name="restaurants_is_active_idx"),
        ),
        migrations.AddIndex(
            model_name="restaurant",
            index=models.Index(fields=["city"], name="restaurants_city_idx"),
        ),
        # Create RestaurantHours model
        migrations.CreateModel(
            name="RestaurantHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as closed for this day (overrides open/close times)",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operating_hours",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "restaurant_hours",
                "ordering": ["day_of_week"],
                "unique_together": {("restaurant", "day_of_week")},
            },
        ),
    ]
