# Generated by Django 5.0.14 on 2025-12-02 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_expand_restaurant_add_hours"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restaurant",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameIndex(
            model_name="restaurant",
            new_name="restaurants_slug_0c26aa_idx",
            old_name="restaurants_slug_idx",
        ),
        migrations.RenameIndex(
            model_name="restaurant",
            new_name="restaurants_is_acti_05aaa6_idx",
            old_name="restaurants_is_active_idx",
        ),
        migrations.RenameIndex(
            model_name="restaurant",
            new_name="restaurants_city_2eac77_idx",
            old_name="restaurants_city_idx",
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in format: '+999999999'. 9-15 digits allowed.",
                        regex="^\\+?[1-9]\\d{8,14}$",
                    )
                ],
            ),
        ),
    ]
