# Generated by Django 5.0.14 on 2026-09-12 11:46

import django.db.models.deletion
import parler.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0013_restaurant_payment_provider_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="warehouse_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Warehouse management: track stock in lots, give dishes recipes, reserve ingredients when customers order and hide dishes whose ingredients have run out. Off by default; nothing changes for the menu until it is on.",
            ),
        ),
    ]
