# Generated by Django 5.0.14 on 2026-09-12 13:06

import django.db.models.deletion
import parler.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0014_warehouse"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantModules",
            fields=[],
            options={
                "verbose_name": "Modules",
                "verbose_name_plural": "Modules",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tenants.restaurant",),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="kitchen_enabled",
            field=models.BooleanField(default=True, help_text="Kitchen display in the POS app. Needs Ordering."),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="loyalty_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Loyalty module: punch-card programs; platform tier discounts are an option inside it.",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="reviews_enabled",
            field=models.BooleanField(
                default=True, help_text="Reviews module: customer reviews on the restaurant page."
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="tables_enabled",
            field=models.BooleanField(
                default=True, help_text="Tables & QR module: sections, tables, QR codes, table sessions, shared venues."
            ),
        ),
    ]
