# Generated by Django 5.0.14 on 2026-09-12 15:46

import django.db.models.deletion
import parler.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0016_cash_module"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="citytranslation",
            options={"default_permissions": (), "managed": True, "verbose_name": "City Translation"},
        ),
        migrations.AddField(
            model_name="restaurant",
            name="printing_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Printing module: kitchen / bar ticket printers and receipt printers through the print bridge (any cheap ESC/POS printer). Off by default; the POS prints receipts through the browser until then.",
            ),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="amenitytranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="tenants.amenity",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="citytranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="tenants.city",
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="accepts_remote_orders",
            field=models.BooleanField(
                default=True,
                help_text="Master ordering switch. When off, customers see the menu but can't order (no cart, no checkout, no QR dine-in ordering). Reservations are controlled separately by accepts_reservations.",
            ),
        ),
        migrations.AlterField(
            model_name="restaurantcategory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="restaurantcategory",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="restaurantcategorytranslation",
            name="master",
            field=parler.fields.TranslationsForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="tenants.restaurantcategory",
            ),
        ),
    ]
