# Generated by Django 5.0.14 on 2026-09-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0017_printing_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="fiscal_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Fiscal module: VAT profile, numbered receipts and refund receipts, RS.ge waybill export.",
            ),
        ),
    ]
