# Generated by Django 5.0.14 on 2026-09-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0018_fiscal_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="delivery_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Delivery platforms module: Glovo orders straight into the kitchen, menu push, sold-out sync.",
            ),
        ),
    ]
