# Generated by Django 5.0.14 on 2026-09-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0024_crm_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="online_ordering_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Online ordering module: pickup and delivery from the restaurant's own page, zones, couriers.",
            ),
        ),
        migrations.AddField(
            model_name="restauranthours",
            name="close_time_2",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restauranthours",
            name="open_time_2",
            field=models.TimeField(blank=True, help_text="Optional second service (e.g. dinner).", null=True),
        ),
        migrations.AlterField(
            model_name="restauranthours",
            name="close_time",
            field=models.TimeField(help_text="Earlier than the opening time = closes after midnight."),
        ),
    ]
