# Generated by Django 5.0.14 on 2026-09-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0025_online_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="terminals_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Card terminals module: physical terminal confirmation, BOG / TBC pay-by-link and QR, ECR bridge.",
            ),
        ),
    ]
