# Generated by Django 5.0.14 on 2026-09-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0026_terminals_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="waitlist_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Waitlist module: today's walk-in queue, quoted waits, 'table ready' SMS, QR at the door.",
            ),
        ),
    ]
