# Generated by Django 5.0.14 on 2026-09-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0027_waitlist_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="gift_cards_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Gift cards module: sell physical / digital cards, redeem at the till or at checkout.",
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="house_accounts_enabled",
            field=models.BooleanField(
                default=False, help_text="House accounts module: regulars and companies on credit, monthly statements."
            ),
        ),
    ]
