# Generated by Django 5.0.14 on 2026-09-12 18:16

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0005_warehouse"),
        ("orders", "0010_source"),
        ("tenants", "0021_promotions_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuSchedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="E.g. 'Breakfast', 'Lunch', 'Happy hour'.", max_length=100)),
                (
                    "weekdays",
                    models.JSONField(blank=True, default=list, help_text="0 = Monday … 6 = Sunday. Empty = every day."),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(help_text="Earlier than the start = the window runs past midnight.")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_schedules",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu schedule",
                "verbose_name_plural": "Menu schedules",
                "db_table": "menu_schedules",
                "ordering": ["start_time", "name"],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.CharField(blank=True, default="", help_text="Shown to guests on the menu.", max_length=300),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("happy_hour", "Happy hour (automatic)"), ("promo_code", "Promo code")],
                        default="happy_hour",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("percent", "Percent off"), ("fixed", "Fixed amount off")],
                        default="percent",
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("all", "Whole order"),
                            ("categories", "Selected categories"),
                            ("items", "Selected dishes"),
                        ],
                        default="all",
                        max_length=12,
                    ),
                ),
                (
                    "code",
                    models.CharField(blank=True, default="", help_text="Guests type this at checkout.", max_length=30),
                ),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("min_order_amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("max_uses", models.PositiveIntegerField(default=0, help_text="0 = unlimited.")),
                ("max_uses_per_customer", models.PositiveIntegerField(default=0, help_text="0 = unlimited.")),
                ("uses_count", models.PositiveIntegerField(default=0)),
                (
                    "channels",
                    models.JSONField(blank=True, default=list, help_text="Empty = everywhere (web, QR, POS)."),
                ),
                (
                    "stackable",
                    models.BooleanField(default=False, help_text="May combine with other promotions on one order."),
                ),
                ("categories", models.ManyToManyField(blank=True, related_name="promotions", to="menu.menucategory")),
                ("items", models.ManyToManyField(blank=True, related_name="promotions", to="menu.menuitem")),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="promotions", to="tenants.restaurant"
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Happy hour: only inside this window. Promo codes: optional restriction.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotions",
                        to="promotions.menuschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion",
                "verbose_name_plural": "Promotions",
                "db_table": "promotions",
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="PromotionUse",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="promotion_uses", to="orders.order"
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="uses", to="promotions.promotion"
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion use",
                "verbose_name_plural": "Promotion uses",
                "db_table": "promotion_uses",
            },
        ),
        migrations.CreateModel(
            name="ComboComponent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="combo_components", to="menu.menuitem"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="in_combos", to="menu.menuitem"
                    ),
                ),
            ],
            options={
                "verbose_name": "Combo component",
                "verbose_name_plural": "Combo components",
                "db_table": "menu_combo_components",
                "ordering": ["display_order"],
                "unique_together": {("combo", "item")},
            },
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code", ""), _negated=True),
                fields=("restaurant", "code"),
                name="promotion_code_unique_per_restaurant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="promotionuse",
            unique_together={("promotion", "order")},
        ),
    ]
