# Generated by Django 5.0.14 on 2026-04-19 22:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options_alter_order_status'),
        ('payments', '0001_initial'),
        ('reservations', '0002_alter_reservationhistory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BogTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bog_order_id', models.CharField(db_index=True, help_text='UUID returned by BOG when the order was created.', max_length=64, unique=True)),
                ('external_order_id', models.CharField(blank=True, db_index=True, help_text='Our reference (Order.order_number, Reservation.confirmation_code, or method_intent_id).', max_length=64)),
                ('flow_type', models.CharField(choices=[('order', 'Order'), ('reservation', 'Reservation'), ('add_card', 'Add Card')], db_index=True, default='order', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='GEL', max_length=3)),
                ('status', models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('auth_requested', 'Pre-auth Requested'), ('blocked', 'Pre-auth Blocked'), ('partial_completed', 'Partially Completed'), ('refund_requested', 'Refund Requested'), ('refunded', 'Refunded'), ('refunded_partially', 'Refunded Partially')], db_index=True, default='created', max_length=32)),
                ('code', models.IntegerField(blank=True, help_text='BOG payment_detail.code (e.g. 100 = success, 107 = insufficient funds).', null=True)),
                ('code_description', models.TextField(blank=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('redirect_url', models.URLField(blank=True, max_length=1024)),
                ('return_url', models.URLField(blank=True, max_length=1024)),
                ('callback_url', models.URLField(blank=True, max_length=1024)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('last_webhook_payload', models.JSONField(blank=True, default=dict)),
                ('last_webhook_at', models.DateTimeField(blank=True, null=True)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'BOG Transaction',
                'verbose_name_plural': 'BOG Transactions',
                'db_table': 'bog_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ['-created_at'], 'verbose_name': 'Refund', 'verbose_name_plural': 'Refunds'},
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_order_i_3d4604_idx',
            old_name='payments_order_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_status_426d4f_idx',
            old_name='payments_status_created_idx',
        ),
        migrations.AddField(
            model_name='bogtransaction',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bog_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bogtransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bog_transactions', to='orders.order'),
        ),
        migrations.AddField(
            model_name='bogtransaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='Populated when this transaction tokenised a card (add_card flow).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bog_transactions', to='payments.paymentmethod'),
        ),
        migrations.AddField(
            model_name='bogtransaction',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bog_transactions', to='reservations.reservation'),
        ),
        migrations.AddIndex(
            model_name='bogtransaction',
            index=models.Index(fields=['flow_type', 'status'], name='bog_transac_flow_ty_a04372_idx'),
        ),
        migrations.AddIndex(
            model_name='bogtransaction',
            index=models.Index(fields=['status', 'created_at'], name='bog_transac_status_17866d_idx'),
        ),
    ]
