# Generated by Django 5.0.14 on 2026-04-20 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_server_order_tip_amount_order_tip_distribution"),
        ("payments", "0002_bogtransaction_alter_payment_options_and_more"),
        ("tables", "0006_tablesession_payment_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="bogtransaction",
            name="covered_orders",
            field=models.ManyToManyField(
                blank=True,
                help_text="Orders this transaction pays off in bulk (session_settle flow). Snapshotted at initiate-time so orders placed after the settle call still require their own payment.",
                related_name="settle_transactions",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="bogtransaction",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="Populated when this transaction settles a whole table (session_settle flow).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bog_transactions",
                to="tables.tablesession",
            ),
        ),
        migrations.AlterField(
            model_name="bogtransaction",
            name="flow_type",
            field=models.CharField(
                choices=[
                    ("order", "Order"),
                    ("reservation", "Reservation"),
                    ("add_card", "Add Card"),
                    ("session_settle", "Session Settle"),
                ],
                db_index=True,
                default="order",
                max_length=20,
            ),
        ),
    ]
