# Generated by Django 5.0.14 on 2026-04-22 10:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_server_order_tip_amount_order_tip_distribution"),
        ("payments", "0003_bogtransaction_covered_orders_bogtransaction_session_and_more"),
        ("reservations", "0002_alter_reservationhistory_options_and_more"),
        ("tables", "0006_tablesession_payment_mode"),
        ("tenants", "0013_restaurant_payment_provider_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bogtransaction",
            name="flow_type",
            field=models.CharField(
                choices=[
                    ("order", "Order"),
                    ("reservation", "Reservation"),
                    ("add_card", "Add Card"),
                    ("session_settle", "Session Settle"),
                    ("cash_settle", "Cash Settle"),
                ],
                db_index=True,
                default="order",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FlittTransaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("flitt_payment_id", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("flitt_order_id", models.CharField(max_length=64, unique=True)),
                (
                    "flow_type",
                    models.CharField(
                        choices=[
                            ("order", "Order"),
                            ("reservation", "Reservation"),
                            ("session_settle", "Session settle"),
                            ("add_card", "Add card"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("processing", "Processing"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("reversed", "Reversed"),
                            ("reversed_partially", "Reversed partially"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=32,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("currency", models.CharField(default="GEL", max_length=3)),
                ("checkout_url", models.URLField(blank=True, default="", max_length=1024)),
                ("return_url", models.URLField(blank=True, default="", max_length=1024)),
                ("callback_url", models.URLField(blank=True, default="", max_length=1024)),
                ("request_payload", models.JSONField(blank=True, null=True)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("last_webhook_payload", models.JSONField(blank=True, null=True)),
                ("last_webhook_at", models.DateTimeField(blank=True, null=True)),
                ("last_reconciled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "settlement_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("pending", "Pending retry"),
                            ("settled", "Settled"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=16,
                    ),
                ),
                ("settlement_id", models.CharField(blank=True, default="", max_length=64)),
                ("settlement_error", models.TextField(blank=True, default="")),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("split_snapshot", models.JSONField(blank=True, null=True)),
                (
                    "covered_orders",
                    models.ManyToManyField(blank=True, related_name="flitt_settle_transactions", to="orders.order"),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flitt_transactions",
                        to="orders.order",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flitt_transactions",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flitt_transactions",
                        to="tables.tablesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flitt Transaction",
                "verbose_name_plural": "Flitt Transactions",
                "db_table": "flitt_transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["flow_type", "status"], name="flitt_trans_flow_ty_fdb486_idx"),
                    models.Index(fields=["status", "created_at"], name="flitt_trans_status_d9df91_idx"),
                    models.Index(fields=["settlement_status"], name="flitt_trans_settlem_0f27df_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RestaurantDebit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("currency", models.CharField(default="GEL", max_length=3)),
                (
                    "source",
                    models.CharField(
                        choices=[("bog_refund", "BOG refund claw-back"), ("manual_adjustment", "Manual adjustment")],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("outstanding", "Outstanding"),
                            ("settled", "Settled"),
                            ("written_off", "Written off"),
                        ],
                        db_index=True,
                        default="outstanding",
                        max_length=16,
                    ),
                ),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="platform_debits",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "settled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_bog_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restaurant_debits",
                        to="payments.bogtransaction",
                    ),
                ),
                (
                    "source_refund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restaurant_debits",
                        to="payments.refund",
                    ),
                ),
            ],
            options={
                "verbose_name": "Restaurant Debit",
                "verbose_name_plural": "Restaurant Debits",
                "db_table": "restaurant_debits",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["restaurant", "status"], name="restaurant__restaur_f5a657_idx"),
                    models.Index(fields=["source", "-created_at"], name="restaurant__source_3ed305_idx"),
                ],
            },
        ),
    ]
