# Generated by Django 5.0.14 on 2026-09-12 14:58

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_discounts"),
        ("payments", "0005_seed_flitt_settlement_beat"),
        ("tables", "0008_tableqrcode_dynamic_destination"),
        ("tenants", "0016_cash_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceiptSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(max_length=30)),
                ("period", models.CharField(blank=True, default="", max_length=10)),
                ("last", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "receipt_sequences",
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="change_given",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="tenants.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="tables.tablesession",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="tendered",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Cash handed over by the customer (cash payments).",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card_terminal", "Card (terminal)"),
                    ("online", "Online provider"),
                    ("voucher", "Voucher"),
                    ("other", "Other"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="Order the refunded amount is taken off (for paid/balance figures).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refunds",
                to="tenants.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="GEL", max_length=3),
        ),
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="The (first) order this payment settles; the full split is in the allocations.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card_terminal", "Card (terminal)"),
                    ("online_bog", "Online (Bank of Georgia)"),
                    ("online_flitt", "Online (Flitt)"),
                    ("voucher", "Voucher"),
                    ("other", "Other"),
                    ("card", "Card"),
                    ("mobile", "Mobile Payment"),
                ],
                default="card",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CashShift",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField(help_text="Sequential per restaurant.")),
                ("register", models.CharField(blank=True, default="", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")], db_index=True, default="open", max_length=10
                    ),
                ),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("opening_float", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("counted_cash", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("expected_cash", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                (
                    "difference",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="counted - expected", max_digits=10, null=True
                    ),
                ),
                ("report", models.JSONField(blank=True, default=dict, help_text="Z report frozen at close.")),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cash_shifts", to="tenants.restaurant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Cash shift",
                "verbose_name_plural": "Cash shifts",
                "db_table": "cash_shifts",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="CashMovement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(choices=[("paid_in", "Paid in"), ("paid_out", "Paid out")], max_length=10)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("reason", models.CharField(max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cash_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="movements", to="payments.cashshift"
                    ),
                ),
            ],
            options={
                "db_table": "cash_movements",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="payments.cashshift",
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds",
                to="payments.cashshift",
            ),
        ),
        migrations.CreateModel(
            name="DiscountReason",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("discount", "Discount"),
                            ("comp", "Comp (on the house)"),
                            ("void", "Void"),
                            ("refund", "Refund"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "requires_manager",
                    models.BooleanField(default=False, help_text="Only roles with 'Cash & payments: edit' may use it."),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discount_reasons",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discount / void reason",
                "verbose_name_plural": "Discount / void reasons",
                "db_table": "discount_reasons",
                "ordering": ["kind", "sort_order", "label"],
            },
        ),
        migrations.AddField(
            model_name="refund",
            name="reason_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds",
                to="payments.discountreason",
            ),
        ),
        migrations.CreateModel(
            name="PaymentAllocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_allocations",
                        to="orders.order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="allocations", to="payments.payment"
                    ),
                ),
            ],
            options={
                "db_table": "payment_allocations",
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="covered_orders",
            field=models.ManyToManyField(
                blank=True, related_name="covering_payments", through="payments.PaymentAllocation", to="orders.order"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["restaurant", "status", "completed_at"], name="payments_restaur_1ce71e_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["shift", "status"], name="payments_shift_i_90915c_idx"),
        ),
        migrations.AddField(
            model_name="receiptsequence",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="receipt_sequences", to="tenants.restaurant"
            ),
        ),
        migrations.AddIndex(
            model_name="cashshift",
            index=models.Index(fields=["restaurant", "status"], name="cash_shifts_restaur_304f2a_idx"),
        ),
        migrations.AddConstraint(
            model_name="cashshift",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("restaurant",),
                name="one_open_cash_shift_per_restaurant",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashshift",
            constraint=models.UniqueConstraint(fields=("restaurant", "number"), name="cash_shift_number_unique"),
        ),
        migrations.AlterUniqueTogether(
            name="paymentallocation",
            unique_together={("payment", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="receiptsequence",
            unique_together={("restaurant", "kind", "period")},
        ),
    ]
