# Generated by Django 5.0.14 on 2026-09-13 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_payment_restaurant_not_null"),
        ("terminals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="terminal",
            field=models.ForeignKey(
                blank=True,
                help_text="The card terminal / pay-by-link that took this payment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="terminals.paymentterminal",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card_terminal", "Card (terminal)"),
                    ("online_bog", "Online (Bank of Georgia)"),
                    ("online_flitt", "Online (Flitt)"),
                    ("online_tbc", "Online (TBC)"),
                    ("voucher", "Voucher"),
                    ("other", "Other"),
                    ("card", "Card"),
                    ("mobile", "Mobile Payment"),
                ],
                default="card",
                max_length=20,
            ),
        ),
    ]
