# Generated by Django 5.0.14 on 2026-09-13 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("giftcards", "0001_initial"),
        ("houseaccounts", "0001_initial"),
        ("payments", "0009_terminal_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="bogtransaction",
            name="gift_card",
            field=models.ForeignKey(
                blank=True,
                help_text="Online gift card purchase this transaction pays for.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="giftcards.giftcard",
            ),
        ),
        migrations.AddField(
            model_name="flitttransaction",
            name="gift_card",
            field=models.ForeignKey(
                blank=True,
                help_text="Online gift card purchase this transaction pays for.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="giftcards.giftcard",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="gift_card",
            field=models.ForeignKey(
                blank=True,
                help_text="Sale of this card (no order) or a redemption against a bill.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="giftcards.giftcard",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="house_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Charge to this account (on a bill) or a settlement of it (no order).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="houseaccounts.houseaccount",
            ),
        ),
        migrations.AlterField(
            model_name="bogtransaction",
            name="flow_type",
            field=models.CharField(
                choices=[
                    ("order", "Order"),
                    ("reservation", "Reservation"),
                    ("add_card", "Add Card"),
                    ("session_settle", "Session Settle"),
                    ("cash_settle", "Cash Settle"),
                    ("gift_card", "Gift card purchase"),
                ],
                db_index=True,
                default="order",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="flitttransaction",
            name="flow_type",
            field=models.CharField(
                choices=[
                    ("order", "Order"),
                    ("reservation", "Reservation"),
                    ("session_settle", "Session settle"),
                    ("add_card", "Add card"),
                    ("gift_card", "Gift card purchase"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card_terminal", "Card (terminal)"),
                    ("online_bog", "Online (Bank of Georgia)"),
                    ("online_flitt", "Online (Flitt)"),
                    ("online_tbc", "Online (TBC)"),
                    ("gift_card", "Gift card"),
                    ("house_account", "House account"),
                    ("voucher", "Voucher"),
                    ("other", "Other"),
                    ("card", "Card"),
                    ("mobile", "Mobile Payment"),
                ],
                default="card",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card_terminal", "Card (terminal)"),
                    ("online", "Online provider"),
                    ("gift_card", "Back to the gift card"),
                    ("house_account", "Back to the house account"),
                    ("voucher", "Voucher"),
                    ("other", "Other"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
