# Generated by Django 5.0.14 on 2026-09-12 16:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0004_report_indexes"),
        ("orders", "0009_vat_snapshot"),
        ("payments", "0008_payment_restaurant_not_null"),
        ("tenants", "0018_fiscal_module"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vat_payer",
                    models.BooleanField(
                        default=False, help_text="Registered VAT payer (turnover above the threshold)."
                    ),
                ),
                ("vat_rate", models.DecimalField(decimal_places=2, default=Decimal("18.00"), max_digits=5)),
                (
                    "prices_include_vat",
                    models.BooleanField(default=True, help_text="Menu prices are gross (VAT included)."),
                ),
                (
                    "legal_name",
                    models.CharField(blank=True, default="", help_text="As registered with RS.", max_length=200),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ს/კ — 9 digits (company) or 11 (individual).",
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator("^(\\d{9}(\\d{2})?)?$", "Tax id is 9 or 11 digits.")
                        ],
                    ),
                ),
                ("legal_address", models.CharField(blank=True, default="", max_length=300)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("none", "Not fiscalised (internal numbering)"),
                            ("rsge_stub", "RS.ge (waybills only, stub)"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("credentials_encrypted", models.TextField(blank=True, default="")),
                ("receipt_prefix", models.CharField(default="R", max_length=8)),
                ("receipt_footer", models.CharField(blank=True, default="", max_length=300)),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_profile",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal profile",
                "verbose_name_plural": "Fiscal profiles",
                "db_table": "fiscal_profiles",
            },
        ),
        migrations.CreateModel(
            name="FiscalSettingsPage",
            fields=[],
            options={
                "verbose_name": "Fiscal settings",
                "verbose_name_plural": "Fiscal settings",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("fiscal.fiscalprofile",),
        ),
        migrations.CreateModel(
            name="FiscalDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("receipt", "Receipt"),
                            ("refund", "Refund receipt"),
                            ("waybill_in", "Inbound waybill"),
                            ("waybill_out", "Outbound waybill"),
                            ("invoice", "E-invoice"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(default="none", max_length=20)),
                ("fiscal_number", models.CharField(blank=True, db_index=True, default="", max_length=40)),
                ("external_id", models.CharField(blank=True, db_index=True, default="", max_length=100)),
                (
                    "is_fiscal",
                    models.BooleanField(
                        default=False, help_text="False = recorded locally only (non-fiscal watermark)."
                    ),
                ),
                ("vat_rate", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("prices_include_vat", models.BooleanField(default=True)),
                ("net_total", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("vat_total", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("gross_total", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("vat_breakdown", models.JSONField(blank=True, default=list)),
                ("lines", models.JSONField(blank=True, default=list)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("response", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True, default="")),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fiscal_documents",
                        to="orders.order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fiscal_documents",
                        to="payments.payment",
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fiscal_documents",
                        to="payments.refund",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fiscal_documents",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "reverses",
                    models.ForeignKey(
                        blank=True,
                        help_text="Refund -> receipt",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversed_by",
                        to="fiscal.fiscaldocument",
                    ),
                ),
                (
                    "stock_lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fiscal_documents",
                        to="inventory.stocklot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal document",
                "verbose_name_plural": "Fiscal documents",
                "db_table": "fiscal_documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["restaurant", "status"], name="fiscal_docu_restaur_f76c75_idx"),
                    models.Index(fields=["restaurant", "kind", "created_at"], name="fiscal_docu_restaur_ba4814_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="fiscaldocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fiscal_number", ""), _negated=True),
                fields=("restaurant", "kind", "fiscal_number"),
                name="fiscal_number_unique_per_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="fiscaldocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "receipt"), models.Q(("status", "cancelled"), _negated=True)),
                fields=("payment",),
                name="one_receipt_per_payment",
            ),
        ),
    ]
