# Generated by Django 5.0.14 on 2025-12-02 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_expand_restaurant_add_hours"),
    ]

    operations = [
        # TableSection
        migrations.CreateModel(
            name="TableSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="table_sections",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "table_sections",
                "ordering": ["display_order", "name"],
                "unique_together": {("restaurant", "name")},
            },
        ),
        # Table
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "number",
                    models.CharField(
                        help_text="Table number or identifier (e.g., '1', 'A1', 'VIP-1')",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional friendly name (e.g., 'Window Table', 'Corner Booth')",
                        max_length=100,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=4, help_text="Maximum number of guests"
                    ),
                ),
                (
                    "min_capacity",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Minimum number of guests for reservation"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("occupied", "Occupied"),
                            ("reserved", "Reserved"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "position_x",
                    models.PositiveIntegerField(
                        blank=True, help_text="X coordinate on floor plan", null=True
                    ),
                ),
                (
                    "position_y",
                    models.PositiveIntegerField(
                        blank=True, help_text="Y coordinate on floor plan", null=True
                    ),
                ),
                (
                    "shape",
                    models.CharField(
                        choices=[
                            ("square", "Square"),
                            ("round", "Round"),
                            ("rectangle", "Rectangle"),
                        ],
                        default="square",
                        max_length=20,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tables",
                        to="tables.tablesection",
                    ),
                ),
            ],
            options={
                "db_table": "tables",
                "ordering": ["section__display_order", "number"],
                "unique_together": {("restaurant", "number")},
            },
        ),
        migrations.AddIndex(
            model_name="table",
            index=models.Index(
                fields=["restaurant", "status"], name="tables_rest_status_idx"
            ),
        ),
        # TableQRCode
        migrations.CreateModel(
            name="TableQRCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name (e.g., 'Main QR', 'Tent Card')",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("scans_count", models.PositiveIntegerField(default=0)),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_codes",
                        to="tables.table",
                    ),
                ),
            ],
            options={
                "db_table": "table_qr_codes",
                "verbose_name": "Table QR Code",
                "verbose_name_plural": "Table QR Codes",
            },
        ),
        # TableSession
        migrations.CreateModel(
            name="TableSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("guest_count", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("payment_pending", "Payment Pending"),
                            ("closed", "Closed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "qr_code",
                    models.ForeignKey(
                        blank=True,
                        help_text="QR code used to start this session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="tables.tableqrcode",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="tables.table",
                    ),
                ),
            ],
            options={
                "db_table": "table_sessions",
                "ordering": ["-started_at"],
            },
        ),
    ]
