# Generated by Django 5.0.14 on 2025-12-02 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="table",
            new_name="tables_restaur_6a4c6c_idx",
            old_name="tables_rest_status_idx",
        ),
    ]
