# Generated by Django 5.0.14 on 2025-12-02 02:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_rename_tables_rest_status_idx_tables_restaur_6a4c6c_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesession',
            name='host',
            field=models.ForeignKey(blank=True, help_text='User who started this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='invite_code',
            field=models.CharField(blank=True, help_text='Shareable code to invite others to this session', max_length=8, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='TableSessionGuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_name', models.CharField(blank=True, help_text='Name for anonymous guests', max_length=100)),
                ('is_host', models.BooleanField(default=False, help_text='Whether this guest is the session host')),
                ('status', models.CharField(choices=[('active', 'Active'), ('left', 'Left')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='tables.tablesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_session_guests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'table_session_guests',
                'ordering': ['-is_host', 'joined_at'],
                'unique_together': {('session', 'user')},
            },
        ),
    ]
