# Generated by Django 5.0.14 on 2026-04-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0004_tableqrcode_qr_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="table",
            options={
                "ordering": ["section__display_order", "number"],
                "verbose_name": "Table",
                "verbose_name_plural": "Tables",
            },
        ),
        migrations.AlterModelOptions(
            name="tablesection",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name": "Table Section",
                "verbose_name_plural": "Table Sections",
            },
        ),
        migrations.AddField(
            model_name="tablesessionguest",
            name="guest_contact",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Phone or email for anonymous guests so the host can reach them.",
                max_length=120,
            ),
        ),
    ]
