# Generated by Django 5.0.14 on 2026-04-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0005_tablesessionguest_guest_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablesession",
            name="payment_mode",
            field=models.CharField(
                choices=[("split", "Everyone pays their own"), ("host_covers", "Host covers the whole table")],
                default="split",
                help_text="split = each guest pays for their own orders. host_covers = the host settles the entire table at the end; guest orders are created without an individual BOG charge.",
                max_length=16,
            ),
        ),
    ]
