# Generated by Django 5.0.14 on 2026-09-12 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0006_tablesession_payment_mode"),
        ("tenants", "0013_restaurant_payment_provider_fields"),
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="venue_table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mirrors",
                to="venues.venuetable",
            ),
        ),
        migrations.AddField(
            model_name="tablesection",
            name="venue_section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mirrors",
                to="venues.venuesection",
            ),
        ),
        migrations.AddConstraint(
            model_name="table",
            constraint=models.UniqueConstraint(
                condition=models.Q(("venue_table__isnull", False)),
                fields=("restaurant", "venue_table"),
                name="uniq_mirror_per_member",
            ),
        ),
        migrations.AddConstraint(
            model_name="tablesection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("venue_section__isnull", False)),
                fields=("restaurant", "venue_section"),
                name="uniq_section_mirror_per_member",
            ),
        ),
    ]
