# Generated by Django 5.0.14 on 2026-09-12 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0007_table_venue_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="tableqrcode",
            name="custom_url",
            field=models.URLField(
                blank=True,
                help_text="Only used when destination is 'Custom URL'.",
                max_length=2000,
                validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
            ),
        ),
        migrations.AddField(
            model_name="tableqrcode",
            name="destination",
            field=models.CharField(
                choices=[
                    ("auto", "Automatic — follows the table (restaurant, or the shared venue)"),
                    ("restaurant", "Always this restaurant's page"),
                    ("venue", "Shared venue page (falls back to the restaurant)"),
                    ("menu_only", "Menu only — browse, no ordering session"),
                    ("custom", "Custom URL"),
                ],
                default="auto",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="tableqrcode",
            name="last_resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tableqrcode",
            name="qr_image_url",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="tableqrcode",
            name="resolves_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
