# Generated by Django 5.0.14 on 2026-09-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0008_tableqrcode_dynamic_destination"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="height",
            field=models.PositiveSmallIntegerField(default=100, help_text="Floor-plan height (logical px)."),
        ),
        migrations.AddField(
            model_name="table",
            name="rotation",
            field=models.PositiveSmallIntegerField(default=0, help_text="Degrees, 0-359, on the floor plan."),
        ),
        migrations.AddField(
            model_name="table",
            name="width",
            field=models.PositiveSmallIntegerField(
                default=100, help_text="Floor-plan width (logical px on a 1000-wide canvas)."
            ),
        ),
        migrations.AddField(
            model_name="tablesection",
            name="background_note",
            field=models.CharField(
                blank=True, default="", help_text="Shown under the section name on the POS floor plan.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="tablesection",
            name="floor_height",
            field=models.PositiveSmallIntegerField(default=700, help_text="Floor-plan canvas height (logical px)."),
        ),
        migrations.AddField(
            model_name="tablesection",
            name="floor_width",
            field=models.PositiveSmallIntegerField(default=1000, help_text="Floor-plan canvas width (logical px)."),
        ),
    ]
