# Generated by Django 5.0.14 on 2026-09-12 11:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0005_warehouse"),
        ("orders", "0006_order_wallet_applied"),
        ("staff", "0002_warehouse"),
        ("tenants", "0014_warehouse"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "dimension",
                    models.CharField(
                        choices=[("mass", "Mass"), ("volume", "Volume"), ("count", "Count")], max_length=10
                    ),
                ),
                ("factor_to_base", models.DecimalField(decimal_places=6, default=1, max_digits=16)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
                "db_table": "inventory_units",
                "ordering": ["dimension", "display_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="InventoryAlert",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("out_of_stock", "Dish sold out"),
                            ("back_in_stock", "Dish back in stock"),
                            ("low_stock", "Low stock"),
                            ("expiring_soon", "Expiring soon"),
                            ("expired", "Expired"),
                            ("negative_stock", "Negative stock"),
                            ("buy_list", "Buy list ready"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(choices=[("open", "Open"), ("done", "Done")], default="open", max_length=10),
                ),
                ("message", models.CharField(max_length=300)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("dedupe_key", models.CharField(max_length=200)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_reason", models.CharField(blank=True, default="", help_text="auto / manual", max_length=20)),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_alerts",
                        to="menu.menuitem",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_alerts",
                        to="menu.modifier",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_inventory_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_alerts",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert",
                "verbose_name_plural": "Alerts",
                "db_table": "inventory_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseOverview",
            fields=[],
            options={
                "verbose_name": "Warehouse overview",
                "verbose_name_plural": "Warehouse overview",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("inventory.inventoryalert",),
        ),
        migrations.CreateModel(
            name="OrderStockReservation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("consumed", "Consumed"),
                            ("released", "Released"),
                            ("restored", "Restored"),
                        ],
                        default="reserved",
                        max_length=10,
                    ),
                ),
                (
                    "strict",
                    models.BooleanField(
                        default=True, help_text="False when a paid order was forced through short stock."
                    ),
                ),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stock_reservation", to="orders.order"
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_reservations",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_order_reservations",
            },
        ),
        migrations.CreateModel(
            name="RestaurantDeliveryPlatform",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("glovo", "Glovo"), ("wolt", "Wolt"), ("bolt_food", "Bolt Food")], max_length=20
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "store_external_id",
                    models.CharField(blank=True, default="", help_text="Your store id there.", max_length=100),
                ),
                ("credentials_encrypted", models.TextField(blank=True, default="")),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_platforms",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery platform",
                "verbose_name_plural": "Delivery platforms (Glovo / Wolt / Bolt Food)",
                "db_table": "inventory_delivery_platforms",
                "ordering": ["platform"],
            },
        ),
        migrations.CreateModel(
            name="InventoryAlertPlatformTask",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(choices=[("disable", "Disable"), ("enable", "Enable")], max_length=10)),
                ("is_done", models.BooleanField(default=False)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "adapter_status",
                    models.CharField(
                        choices=[("manual", "Manual"), ("sent", "Sent via API"), ("failed", "API failed")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("adapter_error", models.TextField(blank=True, default="")),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_tasks",
                        to="inventory.inventoryalert",
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="done_platform_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="inventory.restaurantdeliveryplatform",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_alert_platform_tasks",
                "ordering": ["platform__platform"],
            },
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("sku", models.CharField(blank=True, default="", max_length=50)),
                (
                    "category",
                    models.CharField(
                        blank=True, default="", help_text="Free text, e.g. Dairy, Meat, Dry.", max_length=50
                    ),
                ),
                (
                    "purchase_pack_qty",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Size of one purchase pack in the purchase unit (a 10 kg bag = 10).",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "min_level",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Alert when available stock drops to this (base unit).",
                        max_digits=14,
                    ),
                ),
                (
                    "par_level",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Target stock level the buy list tops up to (base unit).",
                        max_digits=14,
                    ),
                ),
                ("expiry_warning_days", models.PositiveSmallIntegerField(default=3)),
                ("supplier_name", models.CharField(blank=True, default="", max_length=150)),
                (
                    "default_unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Cost per base unit used when no lot cost is known.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("on_hand_qty", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ("reserved_qty", models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stock_items", to="tenants.restaurant"
                    ),
                ),
                (
                    "base_unit",
                    models.ForeignKey(
                        help_text="Unit recipes and counts are kept in (g, ml, pcs).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.unitofmeasure",
                    ),
                ),
                (
                    "purchase_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Unit you buy it in (e.g. kg). Same dimension as the base unit.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.unitofmeasure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock item",
                "verbose_name_plural": "Stock items",
                "db_table": "inventory_stock_items",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("count", "Stock count (I counted this much)"),
                            ("delta", "Correction (+/- this much)"),
                        ],
                        default="count",
                        max_length=10,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4, help_text="Counted amount, or the +/- correction.", max_digits=12
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[("count", "Stock count"), ("correction", "Correction"), ("other", "Other")],
                        default="count",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "delta_base",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Resulting change in base units (filled on save).",
                        max_digits=14,
                    ),
                ),
                (
                    "made_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_adjustments",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="inventory.stockitem",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="inventory.unitofmeasure"
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock count / adjustment",
                "verbose_name_plural": "Stock counts & adjustments",
                "db_table": "inventory_stock_adjustments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderStockReservationLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_reservation_lines",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.orderstockreservation",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation_lines",
                        to="inventory.stockitem",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_order_reservation_lines",
            },
        ),
        migrations.AddField(
            model_name="inventoryalert",
            name="stock_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="inventory.stockitem",
            ),
        ),
        migrations.CreateModel(
            name="EmployeeMeal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("meal_date", models.DateField(default=django.utils.timezone.localdate)),
                ("quantity", models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                ("total_cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_meals",
                        to="menu.menuitem",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_employee_meals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_meals",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        help_text="Who ate.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="meals",
                        to="staff.staffmember",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="For raw ingredients eaten as-is (fruit, bread...).",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_meals",
                        to="inventory.stockitem",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.unitofmeasure",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee meal",
                "verbose_name_plural": "Employee meals",
                "db_table": "inventory_employee_meals",
                "ordering": ["-meal_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockLot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("received_qty", models.DecimalField(decimal_places=4, max_digits=14)),
                ("remaining_qty", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=6, default=0, help_text="Per base unit.", max_digits=12),
                ),
                ("total_cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("supplier_name", models.CharField(blank=True, default="", max_length=150)),
                (
                    "reference",
                    models.CharField(
                        blank=True, default="", help_text="Invoice / delivery note number.", max_length=100
                    ),
                ),
                ("is_expired_out", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_stock_lots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stock_lots", to="tenants.restaurant"
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lots", to="inventory.stockitem"
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock lot",
                "verbose_name_plural": "Stock lots (receiving)",
                "db_table": "inventory_stock_lots",
                "ordering": ["expiry_date", "received_at"],
            },
        ),
        migrations.AddField(
            model_name="inventoryalert",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="inventory.stocklot",
            ),
        ),
        migrations.CreateModel(
            name="RecipeLine",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=12)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "menu_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_lines",
                        to="menu.menuitem",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_lines",
                        to="menu.modifier",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipe_lines",
                        to="inventory.stockitem",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="inventory.unitofmeasure"
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe line",
                "verbose_name_plural": "Recipe lines",
                "db_table": "inventory_recipe_lines",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="WasteEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spoilage", "Spoiled / went bad"),
                            ("expired", "Expired"),
                            ("burnt", "Kitchen mistake (burnt, dropped, wrong dish)"),
                            ("other", "Other"),
                        ],
                        default="spoilage",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("occurred_on", models.DateField(default=django.utils.timezone.localdate)),
                ("total_cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: the exact lot that was thrown away. Otherwise the oldest stock is written off first.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waste_entries",
                        to="inventory.stocklot",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waste_entries",
                        to="staff.staffmember",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waste_entries",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waste_entries",
                        to="inventory.stockitem",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to="inventory.unitofmeasure"
                    ),
                ),
            ],
            options={
                "verbose_name": "Waste / spoilage",
                "verbose_name_plural": "Waste / spoilage / mistakes",
                "db_table": "inventory_waste_entries",
                "ordering": ["-occurred_on", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("receive", "Received"),
                            ("consume_sale", "Consumed by order"),
                            ("restore_sale", "Restored (order cancelled)"),
                            ("waste", "Waste / write-off"),
                            ("employee_meal", "Employee meal"),
                            ("adjustment", "Adjustment / count"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("spoilage", "Spoiled"),
                            ("expired", "Expired"),
                            ("burnt", "Kitchen mistake"),
                            ("count", "Stock count"),
                            ("correction", "Correction"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                ("unit_cost", models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ("total_cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "adjustment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="inventory.stockadjustment",
                    ),
                ),
                (
                    "employee_meal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="inventory.employeemeal",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="inventory.stocklot",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="orders.order",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "staff_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="movements", to="inventory.stockitem"
                    ),
                ),
                (
                    "waste_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="inventory.wasteentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock movement",
                "verbose_name_plural": "Stock movements",
                "db_table": "inventory_stock_movements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="orderstockreservation",
            index=models.Index(fields=["restaurant", "status"], name="inventory_o_restaur_023c93_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="restaurantdeliveryplatform",
            unique_together={("restaurant", "platform")},
        ),
        migrations.AlterUniqueTogether(
            name="inventoryalertplatformtask",
            unique_together={("alert", "platform")},
        ),
        migrations.AddIndex(
            model_name="orderstockreservationline",
            index=models.Index(fields=["stock_item", "is_active"], name="inventory_o_stock_i_b23087_idx"),
        ),
        migrations.AddIndex(
            model_name="stocklot",
            index=models.Index(
                fields=["stock_item", "expiry_date", "received_at"], name="inventory_s_stock_i_fe8eec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocklot",
            index=models.Index(fields=["restaurant", "expiry_date"], name="inventory_s_restaur_8d6ef0_idx"),
        ),
        migrations.AddConstraint(
            model_name="stocklot",
            constraint=models.CheckConstraint(
                check=models.Q(("remaining_qty__gte", 0)), name="inventory_lot_remaining_nonneg"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryalert",
            index=models.Index(fields=["restaurant", "status", "created_at"], name="inventory_a_restaur_fd4bb5_idx"),
        ),
        migrations.AddConstraint(
            model_name="inventoryalert",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("restaurant", "dedupe_key"),
                name="inventory_alert_one_open_per_key",
            ),
        ),
        migrations.AddIndex(
            model_name="stockitem",
            index=models.Index(fields=["restaurant", "is_active"], name="inventory_s_restaur_16589a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="stockitem",
            unique_together={("restaurant", "name")},
        ),
        migrations.AddConstraint(
            model_name="recipeline",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("menu_item__isnull", False), ("modifier__isnull", True)),
                    models.Q(("menu_item__isnull", True), ("modifier__isnull", False)),
                    _connector="OR",
                ),
                name="inventory_recipe_line_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("menu_item__isnull", False)),
                fields=("menu_item", "stock_item"),
                name="inventory_recipe_item_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("modifier__isnull", False)),
                fields=("modifier", "stock_item"),
                name="inventory_recipe_mod_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["restaurant", "created_at"], name="inventory_s_restaur_816dc3_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["stock_item", "created_at"], name="inventory_s_stock_i_50d7d9_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["order"], name="inventory_s_order_i_54acdd_idx"),
        ),
    ]
