# Generated by Django 5.0.14 on 2026-09-12 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_seed_beat"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="employeemeal",
            index=models.Index(fields=["restaurant", "meal_date"], name="inventory_e_restaur_e0e957_idx"),
        ),
        migrations.AddIndex(
            model_name="wasteentry",
            index=models.Index(fields=["restaurant", "occurred_on"], name="inventory_w_restaur_da364a_idx"),
        ),
    ]
