# Generated by Django 5.0.14 on 2026-09-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_report_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantdeliveryplatform",
            name="auto_accept",
            field=models.BooleanField(default=True, help_text="Platform orders go straight to the kitchen."),
        ),
        migrations.AddField(
            model_name="restaurantdeliveryplatform",
            name="last_menu_sync_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurantdeliveryplatform",
            name="last_menu_sync_status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="restaurantdeliveryplatform",
            name="menu_token",
            field=models.CharField(
                blank=True, default="", help_text="Unguessable part of the public menu URL.", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="restaurantdeliveryplatform",
            name="prep_time_minutes",
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="restaurantdeliveryplatform",
            name="sandbox",
            field=models.BooleanField(default=True, help_text="Use the platform's stage environment."),
        ),
        migrations.AddField(
            model_name="restaurantdeliveryplatform",
            name="webhook_token",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
    ]
