# Generated by Django 5.0.14 on 2026-09-12 18:35

import django.db.models.deletion
from django.db import migrations, models


def backfill(apps, schema_editor):
    """Free-text supplier names become Supplier rows (one per restaurant + name)."""
    StockItem = apps.get_model("inventory", "StockItem")
    Supplier = apps.get_model("purchasing", "Supplier")
    for item in StockItem.objects.exclude(supplier_name="").iterator(chunk_size=500):
        name = item.supplier_name.strip()[:150]
        if not name:
            continue
        supplier, _ = Supplier.objects.get_or_create(restaurant_id=item.restaurant_id, name=name)
        StockItem.objects.filter(pk=item.pk).update(supplier=supplier)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_store_paused_until"),
        ("purchasing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Preferred supplier (Purchasing module).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_items",
                to="purchasing.supplier",
            ),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
