# Generated by Django 5.0.14 on 2026-09-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_stock_item_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantdeliveryplatform",
            name="platform",
            field=models.CharField(
                choices=[
                    ("glovo", "Glovo"),
                    ("wolt", "Wolt"),
                    ("bolt_food", "Bolt Food"),
                    ("wolt_drive", "Wolt Drive (courier)"),
                    ("glovo_odr", "Glovo On-Demand (courier)"),
                ],
                max_length=20,
            ),
        ),
    ]
