# Generated by Django 5.0.14 on 2026-09-12 19:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notifications", "0002_seed_beat"),
        ("promotions", "0001_initial"),
        ("tenants", "0024_crm_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Automation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("birthday", "Birthday greeting"),
                            ("review_prompt", "Review prompt after a visit"),
                            ("winback", "Win-back for lapsed guests"),
                        ],
                        max_length=20,
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "channel",
                    models.CharField(choices=[("sms", "SMS"), ("email", "Email")], default="sms", max_length=10),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Placeholders: {name} {restaurant} {code} {link} {unsubscribe}",
                    ),
                ),
                (
                    "delay_hours",
                    models.PositiveSmallIntegerField(default=3, help_text="Review prompt: hours after the visit."),
                ),
                (
                    "lapsed_days",
                    models.PositiveSmallIntegerField(default=45, help_text="Win-back: days without a visit."),
                ),
                ("sent_count", models.PositiveIntegerField(default=0)),
                (
                    "promotion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automations",
                        to="promotions.promotion",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="automations", to="tenants.restaurant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Automation",
                "verbose_name_plural": "Automations",
                "db_table": "crm_automations",
                "unique_together": {("restaurant", "kind")},
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120)),
                (
                    "channel",
                    models.CharField(choices=[("sms", "SMS"), ("email", "Email")], default="sms", max_length=10),
                ),
                ("subject", models.CharField(blank=True, default="", help_text="Email only.", max_length=150)),
                ("body", models.TextField(help_text="Placeholders: {name} {restaurant} {code} {link} {unsubscribe}")),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("audience_count", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        blank=True,
                        help_text="A promo code to include as {code}.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="promotions.promotion",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="campaigns", to="tenants.restaurant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
                "db_table": "crm_campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("phone", models.CharField(blank=True, db_index=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("language", models.CharField(blank=True, default="", max_length=2)),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, help_text="Free tags, e.g. vip, corporate, vegan."),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("marketing_opt_in", models.BooleanField(default=False)),
                ("opt_in_at", models.DateTimeField(blank=True, null=True)),
                ("opt_in_source", models.CharField(blank=True, default="", max_length=30)),
                ("opt_out_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        blank=True, default="", help_text="First contact: qr, web, pos, reservation…", max_length=20
                    ),
                ),
                ("first_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_visit_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_order_at", models.DateTimeField(blank=True, null=True)),
                ("visits", models.PositiveIntegerField(default=0)),
                ("orders_count", models.PositiveIntegerField(default=0)),
                ("reservations_count", models.PositiveIntegerField(default=0)),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                ("total_spend", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("avg_ticket", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("last_rating", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="customers", to="tenants.restaurant"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restaurant_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customers",
                "db_table": "crm_customers",
                "ordering": ["-last_visit_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignDelivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="queued", max_length=10)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="crm.campaign"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="notifications.outboundmessage",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_deliveries",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "db_table": "crm_campaign_deliveries",
            },
        ),
        migrations.CreateModel(
            name="AutomationSend",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        help_text="Order id for review prompts, year for birthdays, month for win-backs.", max_length=64
                    ),
                ),
                (
                    "automation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sends", to="crm.automation"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="notifications.outboundmessage",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="automation_sends", to="crm.customer"
                    ),
                ),
            ],
            options={
                "db_table": "crm_automation_sends",
            },
        ),
        migrations.CreateModel(
            name="Segment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(blank=True, default="", max_length=300)),
                (
                    "rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Keys: min_visits, max_visits, min_spend, last_visit_days_max (visited within N days), last_visit_days_min (no visit for N days), tags_any (list), birthday_month (1-12), has_email, has_phone, opt_in (default true).",
                    ),
                ),
                ("is_builtin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="segments", to="tenants.restaurant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Segment",
                "verbose_name_plural": "Segments",
                "db_table": "crm_segments",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="segment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="campaigns", to="crm.segment"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["restaurant", "marketing_opt_in"], name="crm_custome_restaur_3b270e_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["restaurant", "birthday"], name="crm_custome_restaur_0280ef_idx"),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("phone", ""), _negated=True),
                fields=("restaurant", "phone"),
                name="crm_customer_phone_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("restaurant", "user"),
                name="crm_customer_user_unique",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="campaigndelivery",
            unique_together={("campaign", "customer")},
        ),
        migrations.AlterUniqueTogether(
            name="automationsend",
            unique_together={("automation", "customer", "key")},
        ),
        migrations.AlterUniqueTogether(
            name="segment",
            unique_together={("restaurant", "name")},
        ),
    ]
