# Generated by Django 5.0.14 on 2026-09-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "User Login"),
                    ("logout", "User Logout"),
                    ("login_failed", "Failed Login"),
                    ("password_change", "Password Change"),
                    ("password_reset", "Password Reset"),
                    ("user_create", "User Created"),
                    ("user_update", "User Updated"),
                    ("user_delete", "User Deleted"),
                    ("staff_add", "Staff Added"),
                    ("staff_remove", "Staff Removed"),
                    ("order_create", "Order Created"),
                    ("order_update", "Order Updated"),
                    ("order_cancel", "Order Cancelled"),
                    ("payment_collect", "Payment Collected"),
                    ("settings_update", "Settings Updated"),
                    ("data_export", "Data Exported"),
                    ("stock_receive", "Stock Received"),
                    ("stock_adjust", "Stock Adjusted"),
                    ("stock_waste", "Stock Written Off"),
                    ("employee_meal", "Employee Meal Recorded"),
                    ("recipe_update", "Recipe Updated"),
                    ("warehouse_toggle", "Warehouse Toggled"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
