# Generated by Django 5.0.14 on 2026-09-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0009_waitlist_actions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "User Login"),
                    ("logout", "User Logout"),
                    ("login_failed", "Failed Login"),
                    ("password_change", "Password Change"),
                    ("password_reset", "Password Reset"),
                    ("user_create", "User Created"),
                    ("user_update", "User Updated"),
                    ("user_delete", "User Deleted"),
                    ("staff_add", "Staff Added"),
                    ("staff_remove", "Staff Removed"),
                    ("order_create", "Order Created"),
                    ("order_update", "Order Updated"),
                    ("order_cancel", "Order Cancelled"),
                    ("payment_collect", "Payment Collected"),
                    ("settings_update", "Settings Updated"),
                    ("data_export", "Data Exported"),
                    ("stock_receive", "Stock Received"),
                    ("stock_adjust", "Stock Adjusted"),
                    ("stock_waste", "Stock Written Off"),
                    ("employee_meal", "Employee Meal Recorded"),
                    ("recipe_update", "Recipe Updated"),
                    ("warehouse_toggle", "Warehouse Toggled"),
                    ("shift_open", "Cash Shift Opened"),
                    ("shift_close", "Cash Shift Closed"),
                    ("cash_movement", "Cash Paid In / Out"),
                    ("refund", "Refund Issued"),
                    ("order_discount", "Order Discount"),
                    ("item_comp", "Item Comped"),
                    ("item_void", "Item Voided"),
                    ("order_split", "Order Split"),
                    ("order_move", "Order Moved"),
                    ("menu_availability", "Dish availability changed"),
                    ("po_create", "Purchase order created"),
                    ("po_send", "Purchase order sent"),
                    ("po_receive", "Purchase order received"),
                    ("po_cancel", "Purchase order cancelled"),
                    ("clock_in", "Clocked in"),
                    ("clock_out", "Clocked out"),
                    ("clock_edit", "Time entry edited"),
                    ("rota_publish", "Rota published"),
                    ("price_change", "Price changed"),
                    ("courier_requested", "Courier requested"),
                    ("courier_assigned", "Courier assigned"),
                    ("courier_cancelled", "Courier cancelled"),
                    ("terminal_sale", "Card terminal sale"),
                    ("terminal_refund", "Card terminal refund"),
                    ("waitlist_seated", "Walk-in seated"),
                    ("waitlist_notified", "Walk-in notified"),
                    ("gift_card_issued", "Gift card issued"),
                    ("gift_card_redeemed", "Gift card redeemed"),
                    ("house_account_charge", "Charged to house account"),
                    ("house_account_settle", "House account settled"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
