# Generated by Django 5.0.14 on 2026-09-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
        ("timekeeping", "0002_seed_beat"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoursReport",
            fields=[],
            options={
                "verbose_name": "Hours",
                "verbose_name_plural": "Hours",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("timekeeping.timeentry",),
        ),
    ]
