# Generated by Django 5.0.14 on 2026-09-12 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_seed_beat"),
        ("reports", "0002_hoursreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrmReport",
            fields=[],
            options={
                "verbose_name": "Guests",
                "verbose_name_plural": "Guests",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("crm.customer",),
        ),
    ]
