# Generated by Django 5.0.14 on 2026-09-13 06:55

import apps.ordering.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0011_promotions"),
        ("staff", "0007_crm_resource"),
        ("tenants", "0025_online_ordering"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Courier",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("vehicle", models.CharField(blank=True, default="", help_text="bike / scooter / car", max_length=40)),
                ("is_active", models.BooleanField(default=True)),
                ("is_available", models.BooleanField(default=True, help_text="On shift and taking deliveries.")),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="couriers", to="tenants.restaurant"
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courier_profiles",
                        to="staff.staffmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Courier",
                "verbose_name_plural": "Couriers",
                "db_table": "ordering_couriers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("own", "Own couriers"),
                            ("wolt_drive", "Wolt Drive"),
                            ("glovo_odr", "Glovo On-Demand"),
                        ],
                        default="own",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Not requested"),
                            ("quoted", "Quoted"),
                            ("requested", "Requested"),
                            ("accepted", "Accepted by platform"),
                            ("assigned", "Courier assigned"),
                            ("picked_up", "Picked up"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("external_id", models.CharField(blank=True, db_index=True, default="", max_length=120)),
                ("tracking_url", models.URLField(blank=True, default="", max_length=500)),
                ("quote", models.JSONField(blank=True, default=dict)),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="What the courier platform charges us.", max_digits=10
                    ),
                ),
                (
                    "fee_charged",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="Delivery fee the guest paid.", max_digits=10
                    ),
                ),
                ("pickup_eta", models.DateTimeField(blank=True, null=True)),
                ("dropoff_eta", models.DateTimeField(blank=True, null=True)),
                ("courier_name", models.CharField(blank=True, default="", max_length=120)),
                ("courier_phone", models.CharField(blank=True, default="", max_length=30)),
                ("courier_lat", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("courier_lng", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("events", models.JSONField(blank=True, default=list)),
                ("error", models.TextField(blank=True, default="")),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "courier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="ordering.courier",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="delivery", to="orders.order"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="tenants.restaurant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery",
                "verbose_name_plural": "Deliveries",
                "db_table": "ordering_deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.CharField(max_length=150)),
                ("kind", models.CharField(blank=True, default="", max_length=60)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_events",
                        to="ordering.delivery",
                    ),
                ),
            ],
            options={
                "db_table": "ordering_delivery_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "kind",
                    models.CharField(
                        choices=[("radius", "Radius"), ("polygon", "Polygon")], default="radius", max_length=10
                    ),
                ),
                (
                    "radius_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3"),
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.1"))],
                    ),
                ),
                (
                    "polygon",
                    models.JSONField(blank=True, default=list, help_text="[[lat, lng], ...] for polygon zones."),
                ),
                ("fee", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("min_order", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("eta_minutes", models.PositiveSmallIntegerField(default=45)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sort",
                    models.PositiveSmallIntegerField(default=0, help_text="Lower = checked first (inner ring first)."),
                ),
                ("color", models.CharField(blank=True, default="", max_length=7)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_zones",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Delivery zone",
                "verbose_name_plural": "Delivery zones",
                "db_table": "ordering_delivery_zones",
                "ordering": ["sort", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnlineOrderingSettings",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pickup_enabled", models.BooleanField(default=True, help_text="Guests can order for pickup.")),
                (
                    "delivery_enabled",
                    models.BooleanField(default=False, help_text="Guests can order delivery (needs zones)."),
                ),
                ("asap_enabled", models.BooleanField(default=True, help_text="Allow 'as soon as possible' orders.")),
                (
                    "scheduling_enabled",
                    models.BooleanField(default=True, help_text="Allow choosing a later time slot."),
                ),
                (
                    "lead_minutes",
                    models.PositiveSmallIntegerField(default=30, help_text="Preparation time promised to guests."),
                ),
                (
                    "delivery_extra_minutes",
                    models.PositiveSmallIntegerField(
                        default=20, help_text="Added to the lead time for delivery orders."
                    ),
                ),
                ("slot_interval_minutes", models.PositiveSmallIntegerField(default=15)),
                (
                    "max_days_ahead",
                    models.PositiveSmallIntegerField(
                        default=3, validators=[django.core.validators.MaxValueValidator(30)]
                    ),
                ),
                (
                    "cutoff_minutes_before_close",
                    models.PositiveSmallIntegerField(
                        default=30, help_text="Stop taking online orders this long before closing."
                    ),
                ),
                ("min_order_pickup", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("min_order_delivery", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "free_delivery_over",
                    models.DecimalField(decimal_places=2, default=0, help_text="0 = never free.", max_digits=10),
                ),
                (
                    "packaging_fee",
                    models.DecimalField(decimal_places=2, default=0, help_text="Per order.", max_digits=10),
                ),
                (
                    "courier_provider",
                    models.CharField(
                        choices=[
                            ("own", "Own couriers"),
                            ("wolt_drive", "Wolt Drive"),
                            ("glovo_odr", "Glovo On-Demand"),
                        ],
                        default="own",
                        max_length=20,
                    ),
                ),
                (
                    "auto_request_courier_on",
                    models.CharField(
                        choices=[
                            ("confirmed", "When the order is accepted"),
                            ("ready", "When the order is ready"),
                            ("manual", "Manually from the POS"),
                        ],
                        default="ready",
                        max_length=20,
                    ),
                ),
                (
                    "pass_platform_fee_to_guest",
                    models.BooleanField(
                        default=False, help_text="Charge the guest what Wolt / Glovo quote instead of the zone fee."
                    ),
                ),
                (
                    "paused_until",
                    models.DateTimeField(
                        blank=True, help_text="Online orders paused until then (kitchen slammed).", null=True
                    ),
                ),
                ("pause_reason", models.CharField(blank=True, default="", max_length=120)),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordering_settings",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Online ordering settings",
                "verbose_name_plural": "Online ordering settings",
                "db_table": "ordering_settings",
            },
        ),
        migrations.CreateModel(
            name="OnlineOrderingSettingsPage",
            fields=[],
            options={
                "verbose_name": "Online ordering",
                "verbose_name_plural": "Online ordering",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("ordering.onlineorderingsettings",),
        ),
        migrations.CreateModel(
            name="RestaurantDomain",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("domain", models.CharField(help_text="e.g. order.myrestaurant.ge", max_length=253, unique=True)),
                ("is_primary", models.BooleanField(default=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("last_check_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, default="", max_length=200)),
                (
                    "verification_token",
                    models.CharField(default=apps.ordering.models._domain_token, editable=False, max_length=40),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="domains", to="tenants.restaurant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom domain",
                "verbose_name_plural": "Custom domains",
                "db_table": "ordering_domains",
                "ordering": ["-is_primary", "domain"],
            },
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(fields=["restaurant", "status", "created_at"], name="ordering_de_restaur_d7b118_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="deliveryevent",
            unique_together={("delivery", "event_id")},
        ),
    ]
