# Generated by Django 5.0.14 on 2026-09-12 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0013_restaurant_payment_provider_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="venues/logos/")),
                ("logo_blurhash", models.CharField(blank=True, default="", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Venue",
                "verbose_name_plural": "Venues",
                "db_table": "venues",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VenueMember",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_layout_seed",
                    models.BooleanField(
                        default=False, help_text="This restaurant's tables seeded the venue layout (historical)."
                    ),
                ),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venue_membership",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="venues.venue"
                    ),
                ),
            ],
            options={
                "verbose_name": "Venue member",
                "verbose_name_plural": "Venue members",
                "db_table": "venue_members",
                "ordering": ["display_order", "joined_at"],
            },
        ),
        migrations.CreateModel(
            name="VenueSection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sections", to="venues.venue"
                    ),
                ),
            ],
            options={
                "verbose_name": "Venue section",
                "verbose_name_plural": "Venue sections",
                "db_table": "venue_sections",
                "ordering": ["display_order", "name"],
                "unique_together": {("venue", "name")},
            },
        ),
        migrations.CreateModel(
            name="VenueShareRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "venue_name",
                    models.CharField(
                        blank=True, help_text="Name for the venue if this request creates it", max_length=150
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField()),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "from_restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venue_requests_sent",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="venue_requests_received",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shared venue request",
                "verbose_name_plural": "Shared venue",
                "db_table": "venue_share_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VenueTable",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=20)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("capacity", models.PositiveSmallIntegerField(default=4)),
                ("min_capacity", models.PositiveSmallIntegerField(default=1)),
                (
                    "shape",
                    models.CharField(
                        choices=[("square", "Square"), ("round", "Round"), ("rectangle", "Rectangle")],
                        default="square",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("code", models.CharField(db_index=True, max_length=64, unique=True)),
                ("qr_image", models.ImageField(blank=True, null=True, upload_to="venue_qr_codes/")),
                ("scans_count", models.PositiveIntegerField(default=0)),
                ("last_scanned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tables",
                        to="venues.venuesection",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tables", to="venues.venue"
                    ),
                ),
            ],
            options={
                "verbose_name": "Venue table",
                "verbose_name_plural": "Venue tables",
                "db_table": "venue_tables",
                "ordering": ["section__display_order", "number"],
            },
        ),
        migrations.AddConstraint(
            model_name="venuesharerequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("from_restaurant", "to_restaurant"),
                name="uniq_pending_share_request",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="venuetable",
            unique_together={("venue", "number")},
        ),
    ]
