# Generated by Django 5.0.14 on 2026-09-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venuetable",
            name="last_resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venuetable",
            name="qr_image_url",
            field=models.CharField(blank=True, default="", max_length=2000),
        ),
        migrations.AddField(
            model_name="venuetable",
            name="resolves_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
