# Generated by Django 5.0.14 on 2026-09-13 08:10

import apps.giftcards.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0012_fulfilment"),
        ("payments", "0009_terminal_fk"),
        ("tenants", "0028_gift_house_modules"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftCard",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(db_index=True, default=apps.giftcards.models.new_code, max_length=16, unique=True),
                ),
                ("initial_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="GEL", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting payment"),
                            ("active", "Active"),
                            ("used_up", "Used up"),
                            ("void", "Void"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("physical", "Physical card"), ("digital", "Digital (SMS / email)")],
                        default="physical",
                        max_length=10,
                    ),
                ),
                (
                    "design",
                    models.CharField(
                        choices=[
                            ("classic", "Classic"),
                            ("birthday", "Birthday"),
                            ("thanks", "Thank you"),
                            ("holiday", "Holiday"),
                        ],
                        default="classic",
                        max_length=12,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("purchaser_name", models.CharField(blank=True, default="", max_length=120)),
                ("purchaser_phone", models.CharField(blank=True, default="", max_length=20)),
                ("purchaser_email", models.EmailField(blank=True, default="", max_length=254)),
                ("recipient_name", models.CharField(blank=True, default="", max_length=120)),
                ("recipient_phone", models.CharField(blank=True, default="", max_length=20)),
                ("recipient_email", models.EmailField(blank=True, default="", max_length=254)),
                ("message", models.CharField(blank=True, default="", max_length=300)),
                ("sold_online", models.BooleanField(default=False)),
                (
                    "token",
                    models.CharField(
                        default=apps.giftcards.models.new_token, editable=False, max_length=40, unique=True
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="gift_cards", to="tenants.restaurant"
                    ),
                ),
                (
                    "sold_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sold_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gift_cards_sold",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift card",
                "verbose_name_plural": "Gift cards",
                "db_table": "gift_cards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GiftCardBatchPage",
            fields=[],
            options={
                "verbose_name": "Physical card batch",
                "verbose_name_plural": "Physical card batch",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("giftcards.giftcard",),
        ),
        migrations.CreateModel(
            name="GiftCardTransaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("issue", "Issued"),
                            ("redeem", "Redeemed"),
                            ("refund", "Refunded to card"),
                            ("adjust", "Adjusted"),
                            ("void", "Voided"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, help_text="Signed: + adds to the balance.", max_digits=10),
                ),
                ("balance_after", models.DecimalField(decimal_places=2, max_digits=10)),
                ("note", models.CharField(blank=True, default="", max_length=200)),
                (
                    "by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="giftcards.giftcard",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gift_card_transactions",
                        to="orders.order",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gift_card_transactions",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gift card transaction",
                "verbose_name_plural": "Gift card transactions",
                "db_table": "gift_card_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="giftcard",
            index=models.Index(fields=["restaurant", "status", "created_at"], name="gift_cards_restaur_1a6335_idx"),
        ),
    ]
