# Generated by Django 5.0.14 on 2026-04-21 22:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0005_order_server_order_tip_amount_order_tip_distribution"),
        # Point at the latest tenants migration already on main. Do NOT
        # reference any translation-Meta drift migration that
        # `makemigrations` produces — per CLAUDE.md we strip those so
        # merging this app doesn't pull in unrelated parler metadata
        # changes.
        ("tenants", "0012_restaurant_accepts_platform_loyalty"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=120)),
                ("body", models.TextField(blank=True, default="", max_length=4000)),
                ("is_hidden", models.BooleanField(db_index=True, default=False)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="review", to="orders.order"
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="tenants.restaurant"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "db_table": "reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewMedia",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(choices=[("image", "Image"), ("video", "Video")], max_length=8)),
                ("file", models.FileField(upload_to="reviews/%Y/%m/")),
                ("blurhash", models.CharField(blank=True, default="", max_length=64)),
                ("duration_s", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="media", to="reviews.review"
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Media",
                "verbose_name_plural": "Review Media",
                "db_table": "review_media",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewReport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("offensive", "Offensive"),
                            ("not_a_customer", "Not a real customer"),
                            ("off_topic", "Off topic"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "resolution",
                    models.CharField(
                        choices=[("none", "Open"), ("kept", "Kept"), ("removed", "Removed")],
                        db_index=True,
                        default="none",
                        max_length=16,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_reports_filed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_reports_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reports", to="reviews.review"
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Report",
                "verbose_name_plural": "Review Reports",
                "db_table": "review_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["restaurant", "is_hidden", "-created_at"], name="reviews_restaur_214c70_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["user", "-created_at"], name="reviews_user_id_9f7b05_idx"),
        ),
        migrations.AddIndex(
            model_name="reviewmedia",
            index=models.Index(fields=["review", "position"], name="review_medi_review__b32a00_idx"),
        ),
        migrations.AddIndex(
            model_name="reviewreport",
            index=models.Index(fields=["resolution", "-created_at"], name="review_repo_resolut_3da4c5_idx"),
        ),
        migrations.AddConstraint(
            model_name="reviewreport",
            constraint=models.UniqueConstraint(fields=("review", "reporter"), name="unique_reporter_per_review"),
        ),
    ]
