# Generated by Django 5.0.14 on 2026-09-12 17:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0020_notifications_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("expo", "Expo push"), ("web", "Web push")], default="expo", max_length=10
                    ),
                ),
                ("token", models.CharField(max_length=500, unique=True)),
                ("platform", models.CharField(blank=True, default="", max_length=20)),
                ("app_version", models.CharField(blank=True, default="", max_length=40)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_error", models.CharField(blank=True, default="", max_length=200)),
                (
                    "restaurant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="push_devices",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Push device",
                "verbose_name_plural": "Push devices",
                "db_table": "notification_devices",
            },
        ),
        migrations.CreateModel(
            name="RestaurantNotificationSettings",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guest_sms",
                    models.BooleanField(default=False, help_text="Send SMS to guests (needs an SMS provider)."),
                ),
                (
                    "guest_email",
                    models.BooleanField(default=True, help_text="Send email to guests when they gave an address."),
                ),
                (
                    "sender_name",
                    models.CharField(blank=True, default="", help_text="Shown as the restaurant name.", max_length=60),
                ),
                (
                    "reservation_confirmation_ka",
                    models.TextField(
                        default="{restaurant}: თქვენი მაგიდა დაჯავშნილია {date} {time}-ზე, {guests} სტუმარი. კოდი {code}."
                    ),
                ),
                (
                    "reservation_confirmation_en",
                    models.TextField(
                        default="{restaurant}: your table is booked for {date} at {time}, {guests} guests. Code {code}."
                    ),
                ),
                (
                    "reservation_reminder_ka",
                    models.TextField(default="{restaurant}: შეგახსენებთ, თქვენი ჯავშანი {date} {time}-ზეა. გელოდებით!"),
                ),
                (
                    "reservation_reminder_en",
                    models.TextField(
                        default="{restaurant}: reminder, your reservation is on {date} at {time}. See you soon!"
                    ),
                ),
                (
                    "review_prompt_ka",
                    models.TextField(default="{restaurant}: გმადლობთ სტუმრობისთვის! გაგვიზიარეთ შთაბეჭდილება: {link}"),
                ),
                (
                    "review_prompt_en",
                    models.TextField(default="{restaurant}: thank you for visiting! Tell us how it was: {link}"),
                ),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification settings",
                "verbose_name_plural": "Notification settings",
                "db_table": "notification_settings",
            },
        ),
        migrations.CreateModel(
            name="NotificationSettingsPage",
            fields=[],
            options={
                "verbose_name": "Notification settings",
                "verbose_name_plural": "Notification settings",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("notifications.restaurantnotificationsettings",),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event", models.CharField(db_index=True, max_length=40)),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, help_text="Deep-link payload for the POS (kind, id)."),
                ),
                ("url", models.CharField(blank=True, default="", help_text="Admin page to open.", max_length=300)),
                ("dedupe_key", models.CharField(blank=True, db_index=True, default="", max_length=150)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("pushed_at", models.DateTimeField(blank=True, null=True)),
                ("push_error", models.CharField(blank=True, default="", max_length=200)),
                ("emailed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "read_at", "-created_at"], name="notificatio_user_id_a06a91_idx"),
                    models.Index(fields=["restaurant", "-created_at"], name="notificatio_restaur_dac5c1_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboundMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("channel", models.CharField(choices=[("sms", "SMS"), ("email", "Email")], max_length=10)),
                ("to", models.CharField(max_length=254)),
                ("subject", models.CharField(blank=True, default="", max_length=200)),
                ("body", models.TextField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("reservation_confirmation", "Reservation confirmation"),
                            ("reservation_reminder", "Reservation reminder"),
                            ("review_prompt", "Review prompt"),
                            ("campaign", "Marketing campaign"),
                            ("automation", "Marketing automation"),
                            ("purchase_order", "Purchase order"),
                            ("test", "Test message"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("ref_model", models.CharField(blank=True, default="", max_length=60)),
                ("ref_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "Queued"), ("sent", "Sent"), ("failed", "Failed"), ("skipped", "Skipped")],
                        db_index=True,
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=30)),
                ("provider_id", models.CharField(blank=True, default="", max_length=120)),
                ("error", models.CharField(blank=True, default="", max_length=300)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbound_messages",
                        to="tenants.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outbound message",
                "verbose_name_plural": "Outbound messages",
                "db_table": "notification_outbound_messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["restaurant", "-created_at"], name="notificatio_restaur_1bb0da_idx"),
                    models.Index(fields=["ref_model", "ref_id"], name="notificatio_ref_mod_9d01a1_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StaffNotificationPrefs",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("muted_events", models.JSONField(blank=True, default=list)),
                ("push", models.BooleanField(default=True)),
                ("email", models.BooleanField(default=False)),
                (
                    "quiet_from",
                    models.TimeField(blank=True, help_text="No push between these hours (in-app still).", null=True),
                ),
                ("quiet_to", models.TimeField(blank=True, null=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_prefs",
                        to="tenants.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_prefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff notification preferences",
                "verbose_name_plural": "Staff notification preferences",
                "db_table": "notification_staff_prefs",
                "unique_together": {("restaurant", "user")},
            },
        ),
    ]
