# Generated by Django 5.0.14 on 2026-09-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_seed_beat"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantnotificationsettings",
            name="order_accepted_en",
            field=models.TextField(
                default="{restaurant}: your order {order} is accepted and will be ready around {time}. {link}"
            ),
        ),
        migrations.AddField(
            model_name="restaurantnotificationsettings",
            name="order_accepted_ka",
            field=models.TextField(
                default="{restaurant}: თქვენი შეკვეთა {order} მიღებულია, მზად იქნება დაახლოებით {time}-ზე. {link}"
            ),
        ),
        migrations.AddField(
            model_name="restaurantnotificationsettings",
            name="order_on_the_way_en",
            field=models.TextField(default="{restaurant}: order {order} is on its way. Track it: {tracking_url}"),
        ),
        migrations.AddField(
            model_name="restaurantnotificationsettings",
            name="order_on_the_way_ka",
            field=models.TextField(default="{restaurant}: შეკვეთა {order} გზაშია. თვალი ადევნეთ: {tracking_url}"),
        ),
        migrations.AddField(
            model_name="restaurantnotificationsettings",
            name="order_ready_en",
            field=models.TextField(default="{restaurant}: your order {order} is ready for pickup!"),
        ),
        migrations.AddField(
            model_name="restaurantnotificationsettings",
            name="order_ready_ka",
            field=models.TextField(default="{restaurant}: თქვენი შეკვეთა {order} მზადაა, გელოდებით!"),
        ),
        migrations.AlterField(
            model_name="outboundmessage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reservation_confirmation", "Reservation confirmation"),
                    ("reservation_reminder", "Reservation reminder"),
                    ("review_prompt", "Review prompt"),
                    ("campaign", "Marketing campaign"),
                    ("automation", "Marketing automation"),
                    ("purchase_order", "Purchase order"),
                    ("order_accepted", "Order accepted"),
                    ("order_ready", "Order ready"),
                    ("order_on_the_way", "Order on its way"),
                    ("test", "Test message"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
    ]
