# Generated by Django 5.0.14 on 2026-09-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_order_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantnotificationsettings",
            name="pay_link_en",
            field=models.TextField(default="{restaurant}: {amount} GEL to pay. Pay by card here: {url}"),
        ),
        migrations.AddField(
            model_name="restaurantnotificationsettings",
            name="pay_link_ka",
            field=models.TextField(default="{restaurant}: გადასახდელია {amount} ₾. გადაიხადეთ ბარათით აქ: {url}"),
        ),
        migrations.AlterField(
            model_name="outboundmessage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reservation_confirmation", "Reservation confirmation"),
                    ("reservation_reminder", "Reservation reminder"),
                    ("review_prompt", "Review prompt"),
                    ("campaign", "Marketing campaign"),
                    ("automation", "Marketing automation"),
                    ("purchase_order", "Purchase order"),
                    ("order_accepted", "Order accepted"),
                    ("order_ready", "Order ready"),
                    ("order_on_the_way", "Order on its way"),
                    ("pay_link", "Payment link"),
                    ("test", "Test message"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
    ]
