# Generated by Django 5.0.14 on 2026-09-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_pay_link_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantnotificationsettings",
            name="table_ready_en",
            field=models.TextField(default="{restaurant}: {name}, your table is ready! Please come to the entrance."),
        ),
        migrations.AddField(
            model_name="restaurantnotificationsettings",
            name="table_ready_ka",
            field=models.TextField(
                default="{restaurant}: {name}, თქვენი მაგიდა მზადაა! გთხოვთ, მობრძანდეთ შესასვლელთან."
            ),
        ),
        migrations.AddField(
            model_name="restaurantnotificationsettings",
            name="waitlist_joined_en",
            field=models.TextField(
                default="{restaurant}: you are on the list ({guests} guests), about {minutes} min. Follow it here: {link}"
            ),
        ),
        migrations.AddField(
            model_name="restaurantnotificationsettings",
            name="waitlist_joined_ka",
            field=models.TextField(
                default="{restaurant}: თქვენ რიგში ხართ ({guests} სტუმარი), დაახლ. {minutes} წთ. თვალი ადევნეთ: {link}"
            ),
        ),
        migrations.AlterField(
            model_name="outboundmessage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reservation_confirmation", "Reservation confirmation"),
                    ("reservation_reminder", "Reservation reminder"),
                    ("review_prompt", "Review prompt"),
                    ("campaign", "Marketing campaign"),
                    ("automation", "Marketing automation"),
                    ("purchase_order", "Purchase order"),
                    ("order_accepted", "Order accepted"),
                    ("order_ready", "Order ready"),
                    ("order_on_the_way", "Order on its way"),
                    ("pay_link", "Payment link"),
                    ("waitlist_joined", "Joined the waitlist"),
                    ("table_ready", "Table ready"),
                    ("test", "Test message"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
    ]
