# Generated by Django 5.0.14 on 2026-09-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_waitlist_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantnotificationsettings",
            name="gift_card_en",
            field=models.TextField(default="{restaurant}: a gift card for {amount} GEL. Code {code}. {message} {url}"),
        ),
        migrations.AddField(
            model_name="restaurantnotificationsettings",
            name="gift_card_ka",
            field=models.TextField(default="{restaurant}: სასაჩუქრე ბარათი {amount} ₾. კოდი {code}. {message} {url}"),
        ),
        migrations.AddField(
            model_name="restaurantnotificationsettings",
            name="statement_en",
            field=models.TextField(
                default="{restaurant}: {name}, your statement for {period}: balance {amount} GEL. {url}"
            ),
        ),
        migrations.AddField(
            model_name="restaurantnotificationsettings",
            name="statement_ka",
            field=models.TextField(
                default="{restaurant}: {name}, თქვენი ამონაწერი {period}: დავალიანება {amount} ₾. {url}"
            ),
        ),
        migrations.AlterField(
            model_name="outboundmessage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("reservation_confirmation", "Reservation confirmation"),
                    ("reservation_reminder", "Reservation reminder"),
                    ("review_prompt", "Review prompt"),
                    ("campaign", "Marketing campaign"),
                    ("automation", "Marketing automation"),
                    ("purchase_order", "Purchase order"),
                    ("order_accepted", "Order accepted"),
                    ("order_ready", "Order ready"),
                    ("order_on_the_way", "Order on its way"),
                    ("pay_link", "Payment link"),
                    ("waitlist_joined", "Joined the waitlist"),
                    ("table_ready", "Table ready"),
                    ("gift_card", "Gift card"),
                    ("statement", "House account statement"),
                    ("test", "Test message"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
    ]
